/**
 * Drizzle schema — SSOT for tables, enums and (via types.ts) derived types.
 *
 * EXACT parity with the live database, whose shape was created by the 29
 * Prisma migrations in the repo's history: table/column names are Prisma's
 * PascalCase/camelCase ("PlacementSpot", "createdAt"), enums keep their
 * Prisma type names ("AgeRange"), ids are TEXT minted app-side, timestamps
 * are TIMESTAMP(3), and every index/FK/unique constraint name is pinned to
 * the one Prisma generated ("Resident_code_key", "Placement_residentId_fkey",
 * …) so a fresh database and the live one are byte-identical. Do not
 * "normalize" any of this — the schema must match the database that exists,
 * and the deploy pipeline refuses destructive diffs.
 *
 * Prisma generated cuid() ids and @updatedAt client-side; the equivalents
 * here are $defaultFn(createId) (@paralleldrive/cuid2) and
 * $defaultFn/$onUpdateFn — also app-side, so the columns carry no new DB
 * defaults. Initially generated by drizzle-kit pull against a database built
 * by the Prisma migration chain, then verified by a normalized pg_dump diff
 * (see PR #<n>).
 */

import { createId } from '@paralleldrive/cuid2'
import { sql } from 'drizzle-orm'
import {
  customType,
  pgTable,
  type PgTableExtraConfigValue,
  index,
  text,
  timestamp,
  doublePrecision,
  jsonb,
  integer,
  boolean,
  uniqueIndex,
  foreignKey,
  type AnyPgColumn,
  unique,
  check,
  pgEnum,
} from 'drizzle-orm/pg-core'

// Prisma's `Bytes` -> Postgres bytea. drizzle-orm has no built-in bytea type.
const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return 'bytea'
  },
})

export const activityCategory = pgEnum('ActivityCategory', [
  'SPORT',
  'LANGUAGE',
  'CULTURE',
  'COMMUNITY',
  'FAMILY',
  'SUPPORT',
])
export const activityCost = pgEnum('ActivityCost', ['FREE', 'REDUCED', 'PAID'])
export const activityStatus = pgEnum('ActivityStatus', ['DRAFT', 'PUBLISHED', 'ARCHIVED'])
export const ageRange = pgEnum('AgeRange', ['YOUNG_ADULT', 'ADULT', 'MIDDLE_AGED', 'SENIOR'])
export const agreementStatus = pgEnum('AgreementStatus', [
  'PROPOSED',
  'ACCEPTED',
  'HELD',
  'BROKEN',
  'EXPIRED',
])
export const applicationStage = pgEnum('ApplicationStage', [
  'INTERESTED',
  'APPLIED',
  'INTERVIEW',
  'ACCEPTED',
  'STARTED',
  'ENDED',
  'DECLINED',
])
export const appointmentStatus = pgEnum('AppointmentStatus', [
  'SCHEDULED',
  'COMPLETED',
  'CANCELLED',
  'NO_SHOW',
  'REQUESTED',
])
export const authTokenPurpose = pgEnum('AuthTokenPurpose', ['VERIFY_EMAIL', 'RESET_PASSWORD'])
export const careRole = pgEnum('CareRole', ['HOUSING', 'SOCIAL', 'JOB', 'VOLUNTEERING'])
export const checkInType = pgEnum('CheckInType', ['INITIAL', 'REGULAR', 'AD_HOC', 'EXIT'])
export const complaintStatus = pgEnum('ComplaintStatus', ['OPEN', 'IN_REVIEW', 'ANSWERED'])
export const complaintSubject = pgEnum('ComplaintSubject', [
  'STAFF',
  'ACCOMMODATION',
  'DECISION',
  'OTHER',
])
export const conflictStyle = pgEnum('ConflictStyle', ['AVOIDANT', 'COOPERATIVE', 'DIRECT'])
export const decisionMode = pgEnum('DecisionMode', [
  'RESIDENT_BINDING',
  'RESIDENT_ADVISORY',
  'STAFF_ONLY',
])
export const endReason = pgEnum('EndReason', [
  'NATURAL',
  'CONFLICT',
  'REQUEST',
  'CAPACITY',
  'UPGRADE',
  'OTHER',
])
export const eventRsvpStatus = pgEnum('EventRsvpStatus', ['GOING', 'MAYBE', 'DECLINED'])
export const familyStatus = pgEnum('FamilyStatus', [
  'SINGLE',
  'COUPLE',
  'FAMILY_WITH_CHILDREN',
  'SINGLE_PARENT',
])
export const followUpPriority = pgEnum('FollowUpPriority', ['LOW', 'NORMAL', 'HIGH', 'URGENT'])
export const gender = pgEnum('Gender', ['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_SAY'])
export const houseEventCategory = pgEnum('HouseEventCategory', [
  'HOUSE_MEETING',
  'SOCIAL',
  'CULTURE',
  'SUPPORT',
])
export const houseEventStatus = pgEnum('HouseEventStatus', ['DRAFT', 'PUBLISHED', 'CANCELLED'])
export const householdTaskCategory = pgEnum('HouseholdTaskCategory', [
  'CLEANING',
  'SHOPPING',
  'MAINTENANCE',
  'COOKING',
  'TRASH',
  'OTHER',
])
export const householdTaskPriority = pgEnum('HouseholdTaskPriority', [
  'LOW',
  'NORMAL',
  'HIGH',
  'URGENT',
])
export const householdTaskStatus = pgEnum('HouseholdTaskStatus', [
  'IDLE',
  'NEEDS_ATTENTION',
  'REQUESTED',
  'IN_PROGRESS',
])
export const householdTaskType = pgEnum('HouseholdTaskType', [
  'ONE_TIME',
  'RECURRING_SCHEDULED',
  'RECURRING_AS_NEEDED',
])
export const housingStatus = pgEnum('HousingStatus', ['AVAILABLE', 'FULL', 'MAINTENANCE', 'CLOSED'])
export const incidentCategory = pgEnum('IncidentCategory', [
  'INTERPERSONAL',
  'MAINTENANCE',
  'SAFETY',
  'WELLBEING',
])
export const incidentSeverity = pgEnum('IncidentSeverity', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])
export const incidentType = pgEnum('IncidentType', [
  'NOISE_COMPLAINT',
  'CLEANLINESS_DISPUTE',
  'PERSONAL_CONFLICT',
  'CULTURAL_FRICTION',
  'SPACE_DISPUTE',
  'SCHEDULE_CONFLICT',
  'SAFETY_CONCERN',
  'PLUMBING',
  'ELECTRICAL',
  'HEATING_COOLING',
  'APPLIANCE',
  'STRUCTURAL',
  'PEST_CONTROL',
  'SECURITY_SYSTEM',
  'GENERAL_MAINTENANCE',
  'LOW_SATISFACTION',
  'OTHER',
])
export const interpreterNeed = pgEnum('InterpreterNeed', ['NONE', 'FOR_COMPLEX', 'ALWAYS'])
export const involvementRole = pgEnum('InvolvementRole', ['INVOLVED', 'WITNESS', 'MEDIATOR'])
export const learningKind = pgEnum('LearningKind', [
  'LANGUAGE_TEST',
  'COURSE',
  'INFORMAL',
  'QUALIFICATION',
  'VOLUNTEERING',
  'COMMUNITY_SERVICE',
  'EMPLOYMENT',
  'INTERNSHIP',
])
export const learningStatus = pgEnum('LearningStatus', [
  'PLANNED',
  'IN_PROGRESS',
  'COMPLETED',
  'EXPIRED',
])
export const livingSkillsSupport = pgEnum('LivingSkillsSupport', [
  'INDEPENDENT',
  'SOME_SUPPORT',
  'REGULAR_SUPPORT',
])
export const maintenanceCategory = pgEnum('MaintenanceCategory', [
  'PLUMBING',
  'ELECTRICAL',
  'HEATING_COOLING',
  'APPLIANCE',
  'STRUCTURAL',
  'PEST_CONTROL',
  'SECURITY',
  'CLEANING',
  'EXTERIOR',
  'OTHER',
])
export const maintenancePriority = pgEnum('MaintenancePriority', [
  'LOW',
  'NORMAL',
  'HIGH',
  'URGENT',
])
export const maintenanceStatus = pgEnum('MaintenanceStatus', [
  'OPEN',
  'ASSIGNED',
  'IN_PROGRESS',
  'ON_HOLD',
  'COMPLETED',
  'CANCELLED',
])
export const marketplacePostKind = pgEnum('MarketplacePostKind', [
  'GIVE_AWAY',
  'LEND',
  'WANTED',
  'OFFER_HELP',
  'NEED_HELP',
])
export const marketplacePostStatus = pgEnum('MarketplacePostStatus', ['OPEN', 'CLAIMED', 'CLOSED'])
export const medicalDocType = pgEnum('MedicalDocType', ['PRIVATE_ROOM', 'STUDIO', 'BOTH'])
export const mobilityNeed = pgEnum('MobilityNeed', ['NONE', 'GROUND_FLOOR', 'WHEELCHAIR'])
export const opportunityKind = pgEnum('OpportunityKind', [
  'VOLUNTEERING',
  'COMMUNITY_SERVICE',
  'EMPLOYMENT',
  'INTERNSHIP',
])
export const opportunityStatus = pgEnum('OpportunityStatus', ['DRAFT', 'PUBLISHED', 'ARCHIVED'])
export const permitRequirement = pgEnum('PermitRequirement', [
  'NONE',
  'EMPLOYER_NOTIFIES',
  'PERMIT_REQUIRED',
])
export const placementStatus = pgEnum('PlacementStatus', ['ACTIVE', 'ENDED', 'TRANSFERRED'])
export const profileVisibility = pgEnum('ProfileVisibility', ['PRIVATE', 'ROOMMATES', 'RESIDENTS'])
export const proposalStatus = pgEnum('ProposalStatus', [
  'DISCUSSION',
  'VOTING',
  'NEEDS_STAFF_CONFIRMATION',
  'ACCEPTED',
  'REJECTED',
  'WITHDRAWN',
  'VETOED',
  'EXPIRED',
])
export const proposalType = pgEnum('ProposalType', [
  'ADD_RULE',
  'AMEND_RULE',
  'REPEAL_RULE',
  'HOUSE_DECISION',
])
export const recyclingKnowledge = pgEnum('RecyclingKnowledge', ['NONE', 'BASIC', 'GOOD'])
export const residentOrStaff = pgEnum('ResidentOrStaff', ['RESIDENT', 'STAFF'])
export const residentStatus = pgEnum('ResidentStatus', [
  'ACTIVE',
  'PLACED',
  'TRANSFERRED',
  'EXITED',
])
export const resolutionStage = pgEnum('ResolutionStage', [
  'REPORTED',
  'SELF_RESOLUTION',
  'PEER_MEDIATION',
  'STAFF_MEDIATION',
  'FORMAL_MEASURE',
  'CLOSED',
])
export const roomSharingStatus = pgEnum('RoomSharingStatus', [
  'CAN_SHARE',
  'PREFERS_PRIVATE',
  'NEEDS_PRIVATE',
])
export const ruleCategory = pgEnum('RuleCategory', [
  'SAFETY',
  'RESPECT',
  'NOISE',
  'CLEANLINESS',
  'KITCHEN',
  'BATHROOM',
  'GUESTS',
  'SHARED_SPACES',
  'COSTS',
  'COMMUNICATION',
  'OTHER',
])
export const ruleDelegation = pgEnum('RuleDelegation', [
  'FIXED',
  'UNIT_MAY_STRENGTHEN',
  'UNIT_DECIDES',
])
export const ruleScope = pgEnum('RuleScope', ['ORG', 'UNIT'])
export const ruleStatus = pgEnum('RuleStatus', ['ACTIVE', 'SUPERSEDED', 'ARCHIVED'])
export const siteAccess = pgEnum('SiteAccess', ['ALL_UNITS', 'ASSIGNED_UNITS'])
export const sleepSchedule = pgEnum('SleepSchedule', [
  'EARLY_BIRD',
  'STANDARD',
  'NIGHT_OWL',
  'IRREGULAR',
])
export const smokingStatus = pgEnum('SmokingStatus', [
  'NON_SMOKER',
  'OUTDOOR_SMOKER',
  'INDOOR_SMOKER',
])
export const socialStyle = pgEnum('SocialStyle', ['INTROVERTED', 'MODERATE', 'EXTROVERTED'])
export const spotStatus = pgEnum('SpotStatus', ['AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'CLOSED'])
export const spotType = pgEnum('SpotType', ['BED', 'PRIVATE_ROOM', 'STUDIO', 'ROOM'])
export const staffDecision = pgEnum('StaffDecision', ['CONFIRMED', 'VETOED'])
export const staffRole = pgEnum('StaffRole', [
  'ADMIN',
  'BETREUUNG',
  'SOZIALARBEIT',
  'JOBCOACH',
  'FREIWILLIGENARBEIT',
])
export const staffScope = pgEnum('StaffScope', ['OWN_DOMAIN', 'ALL_DOMAINS'])
export const supportLevel = pgEnum('SupportLevel', ['STANDARD', 'ELEVATED', 'INTENSIVE'])
export const taskRequestStatus = pgEnum('TaskRequestStatus', [
  'PENDING',
  'ACCEPTED',
  'DECLINED',
  'COMPLETED',
])
export const transferRequestStatus = pgEnum('TransferRequestStatus', [
  'PENDING',
  'APPROVED',
  'DENIED',
  'COMPLETED',
  'CANCELLED',
])
export const voteChoice = pgEnum('VoteChoice', ['YES', 'NO', 'ABSTAIN', 'BLOCK'])
export const voteThreshold = pgEnum('VoteThreshold', [
  'CONSENSUS',
  'SUPERMAJORITY',
  'SIMPLE_MAJORITY',
])

export const algorithmWeight = pgTable(
  'AlgorithmWeight',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    lifestyleWeight: doublePrecision().default(30).notNull(),
    socialWeight: doublePrecision().default(25).notNull(),
    practicalWeight: doublePrecision().default(25).notNull(),
    riskWeight: doublePrecision().default(20).notNull(),
    factorWeights: jsonb().notNull(),
    version: integer().default(1).notNull(),
    active: boolean().default(true).notNull(),
    notes: text(),
  },
  (table) => [index('AlgorithmWeight_active_idx').using('btree', table.active.asc().nullsLast())],
)

export const placementSpot = pgTable(
  'PlacementSpot',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    code: text().notNull(),
    label: text(),
    type: spotType().notNull(),
    parentSpotId: text(),
    squareMeters: doublePrecision(),
    floor: integer(),
    hasPrivateBathroom: boolean().default(false).notNull(),
    hasPrivateKitchen: boolean().default(false).notNull(),
    hasPrivateToilet: boolean().default(false).notNull(),
    capacity: integer().default(1).notNull(),
    requiresMedicalDocs: boolean().default(false).notNull(),
    status: spotStatus().default('AVAILABLE').notNull(),
    notes: text(),
  },
  (table) => [
    uniqueIndex('PlacementSpot_housingUnitId_code_key').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.code.asc().nullsLast(),
    ),
    index('PlacementSpot_housingUnitId_idx').using('btree', table.housingUnitId.asc().nullsLast()),
    index('PlacementSpot_requiresMedicalDocs_idx').using(
      'btree',
      table.requiresMedicalDocs.asc().nullsLast(),
    ),
    index('PlacementSpot_type_status_idx').using(
      'btree',
      table.type.asc().nullsLast(),
      table.status.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'PlacementSpot_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.parentSpotId],
      foreignColumns: [table.id],
      name: 'PlacementSpot_parentSpotId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const placement = pgTable(
  'Placement',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    housingUnitId: text().notNull(),
    spotId: text(),
    startDate: timestamp({ precision: 3, mode: 'date' }).notNull(),
    endDate: timestamp({ precision: 3, mode: 'date' }),
    compatibilityScore: doublePrecision(),
    lifestyleScore: doublePrecision(),
    socialScore: doublePrecision(),
    practicalScore: doublePrecision(),
    riskScore: doublePrecision(),
    status: placementStatus().default('ACTIVE').notNull(),
    endReason: endReason(),
    satisfactionRating: integer(),
    placementNotes: text(),
    outcomeNotes: text(),
    conflictGap: text(),
    wasPredictable: boolean(),
    relatedIncidentId: text(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('Placement_housingUnitId_idx').using('btree', table.housingUnitId.asc().nullsLast()),
    uniqueIndex('Placement_residentId_housingUnitId_startDate_key').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.housingUnitId.asc().nullsLast(),
      table.startDate.asc().nullsLast(),
    ),
    index('Placement_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    index('Placement_startDate_endDate_idx').using(
      'btree',
      table.startDate.asc().nullsLast(),
      table.endDate.asc().nullsLast(),
    ),
    index('Placement_status_idx').using('btree', table.status.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'Placement_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'Placement_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.spotId],
      foreignColumns: [placementSpot.id],
      name: 'Placement_spotId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.relatedIncidentId],
      // Cast breaks the type-level cycle (Placement <-> Incident reference
      // each other); the generated DDL is unchanged.
      foreignColumns: [incident.id as AnyPgColumn],
      name: 'Placement_relatedIncidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const compatibilityAssessment = pgTable(
  'CompatibilityAssessment',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    residentId: text().notNull(),
    comparedWithId: text().notNull(),
    overallScore: doublePrecision().notNull(),
    lifestyleScore: doublePrecision().notNull(),
    socialScore: doublePrecision().notNull(),
    practicalScore: doublePrecision().notNull(),
    riskScore: doublePrecision().notNull(),
    strengths: text().array(),
    concerns: text().array(),
    recommendations: text().array(),
  },
  (table) => [
    index('CompatibilityAssessment_overallScore_idx').using(
      'btree',
      table.overallScore.asc().nullsLast(),
    ),
    uniqueIndex('CompatibilityAssessment_residentId_comparedWithId_key').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.comparedWithId.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'CompatibilityAssessment_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.comparedWithId],
      foreignColumns: [resident.id],
      name: 'CompatibilityAssessment_comparedWithId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const incidentFollowUp = pgTable(
  'IncidentFollowUp',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    incidentId: text().notNull(),
    action: text().notNull(),
    notes: text(),
    outcome: text(),
    staffName: text(),
    scheduledNextDate: timestamp({ precision: 3, mode: 'date' }),
  },
  (table) => [
    index('IncidentFollowUp_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('IncidentFollowUp_incidentId_idx').using('btree', table.incidentId.asc().nullsLast()),
    foreignKey({
      columns: [table.incidentId],
      foreignColumns: [incident.id],
      name: 'IncidentFollowUp_incidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const incidentInvolvement = pgTable(
  'IncidentInvolvement',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    incidentId: text().notNull(),
    residentId: text().notNull(),
    role: involvementRole().default('INVOLVED').notNull(),
  },
  (table) => [
    uniqueIndex('IncidentInvolvement_incidentId_residentId_key').using(
      'btree',
      table.incidentId.asc().nullsLast(),
      table.residentId.asc().nullsLast(),
    ),
    index('IncidentInvolvement_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    foreignKey({
      columns: [table.incidentId],
      foreignColumns: [incident.id],
      name: 'IncidentInvolvement_incidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'IncidentInvolvement_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const auditLog = pgTable(
  'AuditLog',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    action: text().notNull(),
    entity: text().notNull(),
    entityId: text().notNull(),
    userId: text(),
    changes: jsonb(),
    reason: text(),
  },
  (table) => [
    index('AuditLog_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('AuditLog_entity_entityId_idx').using(
      'btree',
      table.entity.asc().nullsLast(),
      table.entityId.asc().nullsLast(),
    ),
    index('AuditLog_userId_idx').using('btree', table.userId.asc().nullsLast()),
    foreignKey({
      columns: [table.userId],
      foreignColumns: [user.id],
      name: 'AuditLog_userId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const maintenanceRequest = pgTable(
  'MaintenanceRequest',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    spotId: text(),
    category: maintenanceCategory().notNull(),
    priority: maintenancePriority().default('NORMAL').notNull(),
    title: text().notNull(),
    description: text().notNull(),
    location: text(),
    reportedById: text(),
    reporterName: text(),
    assignedTo: text(),
    assignedAt: timestamp({ precision: 3, mode: 'date' }),
    status: maintenanceStatus().default('OPEN').notNull(),
    startedAt: timestamp({ precision: 3, mode: 'date' }),
    completedAt: timestamp({ precision: 3, mode: 'date' }),
    resolution: text(),
    cost: doublePrecision(),
    notes: text(),
  },
  (table) => [
    index('MaintenanceRequest_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('MaintenanceRequest_housingUnitId_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
    ),
    index('MaintenanceRequest_priority_status_idx').using(
      'btree',
      table.priority.asc().nullsLast(),
      table.status.asc().nullsLast(),
    ),
    index('MaintenanceRequest_reportedById_idx').using(
      'btree',
      table.reportedById.asc().nullsLast(),
    ),
    index('MaintenanceRequest_status_idx').using('btree', table.status.asc().nullsLast()),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'MaintenanceRequest_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.spotId],
      foreignColumns: [placementSpot.id],
      name: 'MaintenanceRequest_spotId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.reportedById],
      foreignColumns: [resident.id],
      name: 'MaintenanceRequest_reportedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const taskAttentionFlag = pgTable(
  'TaskAttentionFlag',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    taskId: text().notNull(),
    flaggedById: text().notNull(),
    message: text(),
    isResolved: boolean().default(false).notNull(),
    resolvedAt: timestamp({ precision: 3, mode: 'date' }),
    resolvedByCompletionId: text(),
  },
  (table) => [
    index('TaskAttentionFlag_taskId_idx').using('btree', table.taskId.asc().nullsLast()),
    foreignKey({
      columns: [table.taskId],
      foreignColumns: [householdTask.id],
      name: 'TaskAttentionFlag_taskId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.flaggedById],
      foreignColumns: [resident.id],
      name: 'TaskAttentionFlag_flaggedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.resolvedByCompletionId],
      foreignColumns: [taskCompletion.id],
      name: 'TaskAttentionFlag_resolvedByCompletionId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const housingUnit = pgTable(
  'HousingUnit',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    code: text().notNull(),
    address: text().notNull(),
    totalBeds: integer().notNull(),
    totalRooms: integer().notNull(),
    sharedRooms: integer().notNull(),
    privateRooms: integer().notNull(),
    sharedBathrooms: integer().notNull(),
    privateBathrooms: integer().notNull(),
    sharedKitchen: boolean().default(true).notNull(),
    privateKitchen: boolean().default(false).notNull(),
    groundFloor: boolean().default(false).notNull(),
    wheelchairAccess: boolean().default(false).notNull(),
    elevator: boolean().default(false).notNull(),
    smokingAllowed: boolean().default(false).notNull(),
    petsAllowed: boolean().default(false).notNull(),
    quietHours: text(),
    nearPublicTransport: boolean().default(true).notNull(),
    nearHealthServices: boolean().default(false).notNull(),
    nearSchools: boolean().default(false).notNull(),
    status: housingStatus().default('AVAILABLE').notNull(),
    notes: text(),
    nickname: text(),
    buildingCode: text(),
  },
  (table) => [
    index('HousingUnit_buildingCode_idx').using('btree', table.buildingCode.asc().nullsLast()),
    uniqueIndex('HousingUnit_code_key').using('btree', table.code.asc().nullsLast()),
    index('HousingUnit_status_idx').using('btree', table.status.asc().nullsLast()),
    index('HousingUnit_totalBeds_idx').using('btree', table.totalBeds.asc().nullsLast()),
  ],
)

export const householdTask = pgTable(
  'HouseholdTask',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    title: text().notNull(),
    description: text(),
    instructions: text(),
    taskType: householdTaskType().default('ONE_TIME').notNull(),
    category: householdTaskCategory().default('OTHER').notNull(),
    priority: householdTaskPriority().default('NORMAL').notNull(),
    scheduleHuman: text(),
    estimatedMinutes: integer(),
    currentStatus: householdTaskStatus().default('IDLE').notNull(),
    isCompleted: boolean().default(false).notNull(),
    completedAt: timestamp({ precision: 3, mode: 'date' }),
    createdByResidentId: text(),
    createdByStaff: text(),
    checklist: text()
      .array()
      .default(sql`ARRAY[]::TEXT[]`),
    rotationResidentIds: text()
      .array()
      .default(sql`ARRAY[]::TEXT[]`),
  },
  (table) => [
    index('HouseholdTask_housingUnitId_category_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.category.asc().nullsLast(),
    ),
    index('HouseholdTask_housingUnitId_currentStatus_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.currentStatus.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'HouseholdTask_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.createdByResidentId],
      foreignColumns: [resident.id],
      name: 'HouseholdTask_createdByResidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const satisfactionCheckIn = pgTable(
  'SatisfactionCheckIn',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    placementId: text().notNull(),
    checkInType: checkInType().notNull(),
    weekNumber: integer(),
    overallSatisfaction: integer().notNull(),
    roommateRelations: integer(),
    facilitySatisfaction: integer(),
    safetyFeeling: integer(),
    concerns: text(),
    improvements: text(),
    positives: text(),
    collectedBy: text(),
    isAnonymous: boolean().default(false).notNull(),
    appointmentId: text(),
    collectedByUserId: text(),
  },
  (table) => [
    uniqueIndex('SatisfactionCheckIn_appointmentId_key').using(
      'btree',
      table.appointmentId.asc().nullsLast(),
    ),
    index('SatisfactionCheckIn_checkInType_idx').using(
      'btree',
      table.checkInType.asc().nullsLast(),
    ),
    index('SatisfactionCheckIn_collectedByUserId_idx').using(
      'btree',
      table.collectedByUserId.asc().nullsLast(),
    ),
    index('SatisfactionCheckIn_placementId_idx').using(
      'btree',
      table.placementId.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.placementId],
      foreignColumns: [placement.id],
      name: 'SatisfactionCheckIn_placementId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.appointmentId],
      foreignColumns: [appointment.id],
      name: 'SatisfactionCheckIn_appointmentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.collectedByUserId],
      foreignColumns: [user.id],
      name: 'SatisfactionCheckIn_collectedByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const user = pgTable(
  'User',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    name: text().notNull(),
    role: staffRole().default('BETREUUNG').notNull(),
    active: boolean().default(true).notNull(),
    lastLoginAt: timestamp({ precision: 3, mode: 'date' }),
    code: text().notNull(),
    scope: staffScope().default('OWN_DOMAIN').notNull(),
    isSystemAdmin: boolean().default(false).notNull(),
    siteAccess: siteAccess().default('ALL_UNITS').notNull(),
  },
  (table) => [
    index('User_code_idx').using('btree', table.code.asc().nullsLast()),
    index('User_role_idx').using('btree', table.role.asc().nullsLast()),
    index('User_scope_idx').using('btree', table.scope.asc().nullsLast()),
    unique('User_code_key').on(table.code),
  ],
)

export const taskRequest = pgTable(
  'TaskRequest',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    taskId: text().notNull(),
    requestedById: text().notNull(),
    requestedResidentId: text(),
    isBroadcast: boolean().default(false).notNull(),
    message: text(),
    status: taskRequestStatus().default('PENDING').notNull(),
    responseMessage: text(),
    completionId: text(),
  },
  (table) => [
    index('TaskRequest_requestedResidentId_idx').using(
      'btree',
      table.requestedResidentId.asc().nullsLast(),
    ),
    index('TaskRequest_taskId_idx').using('btree', table.taskId.asc().nullsLast()),
    foreignKey({
      columns: [table.taskId],
      foreignColumns: [householdTask.id],
      name: 'TaskRequest_taskId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.requestedById],
      foreignColumns: [resident.id],
      name: 'TaskRequest_requestedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.requestedResidentId],
      foreignColumns: [resident.id],
      name: 'TaskRequest_requestedResidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.completionId],
      foreignColumns: [taskCompletion.id],
      name: 'TaskRequest_completionId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const transferRequest = pgTable(
  'TransferRequest',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    currentPlacementId: text(),
    targetUnitId: text(),
    reason: text().notNull(),
    status: transferRequestStatus().default('PENDING').notNull(),
    staffNotes: text(),
    reviewedBy: text(),
    reviewedAt: timestamp({ precision: 3, mode: 'date' }),
  },
  (table) => [
    index('TransferRequest_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    index('TransferRequest_status_idx').using('btree', table.status.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'TransferRequest_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.currentPlacementId],
      foreignColumns: [placement.id],
      name: 'TransferRequest_currentPlacementId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.targetUnitId],
      foreignColumns: [housingUnit.id],
      name: 'TransferRequest_targetUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const resident = pgTable(
  'Resident',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    code: text().notNull(),
    ageRange: ageRange().notNull(),
    gender: gender().notNull(),
    familyStatus: familyStatus().notNull(),
    sleepSchedule: sleepSchedule().notNull(),
    noiseTolerance: integer().notNull(),
    cleanlinessPractice: integer().notNull(),
    guestTolerance: integer().default(3).notNull(),
    socialStyle: socialStyle().notNull(),
    languages: text().array(),
    culturalRegion: text(),
    conflictStyle: conflictStyle().default('COOPERATIVE').notNull(),
    smokingStatus: smokingStatus().notNull(),
    dietaryNeeds: text().array(),
    mobilityNeeds: mobilityNeed().notNull(),
    medicalEquipment: boolean().default(false).notNull(),
    petTolerance: boolean().default(true).notNull(),
    sharedBathroom: boolean().default(true).notNull(),
    sharedKitchen: boolean().default(true).notNull(),
    privacyNeed: integer().notNull(),
    choresContribution: integer().default(3).notNull(),
    recyclingKnowledge: recyclingKnowledge().default('NONE').notNull(),
    roomSharingStatus: roomSharingStatus().default('CAN_SHARE').notNull(),
    hasNightDisturbances: boolean().default(false).notNull(),
    needsQuietEnvironment: boolean().default(false).notNull(),
    hasSleepEquipment: boolean().default(false).notNull(),
    supportLevel: supportLevel().default('STANDARD').notNull(),
    interpreterNeed: interpreterNeed().default('NONE').notNull(),
    roommatePreferences: text(),
    status: residentStatus().default('ACTIVE').notNull(),
    notes: text(),
    hasMedicalDocumentation: boolean().default(false).notNull(),
    medicalDocType: medicalDocType(),
    medicalDocDate: timestamp({ precision: 3, mode: 'date' }),
    medicalDocNotes: text(),
    preferencesCompletedAt: timestamp({ precision: 3, mode: 'date' }),
    cleanlinessExpectation: integer().default(3).notNull(),
    chaosTolerance: integer().default(3).notNull(),
    bio: text(),
    displayName: text(),
    profileVisibility: profileVisibility().default('ROOMMATES').notNull(),
    livingSkillsSupport: livingSkillsSupport().default('INDEPENDENT').notNull(),
  },
  (table) => [
    index('Resident_ageRange_gender_idx').using(
      'btree',
      table.ageRange.asc().nullsLast(),
      table.gender.asc().nullsLast(),
    ),
    uniqueIndex('Resident_code_key').using('btree', table.code.asc().nullsLast()),
    index('Resident_livingSkillsSupport_idx').using(
      'btree',
      table.livingSkillsSupport.asc().nullsLast(),
    ),
    index('Resident_status_idx').using('btree', table.status.asc().nullsLast()),
    index('Resident_interpreterNeed_idx').using('btree', table.interpreterNeed.asc().nullsLast()),
  ],
)

export const activity = pgTable(
  'Activity',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    title: text().notNull(),
    description: text().notNull(),
    category: activityCategory().notNull(),
    cost: activityCost().default('FREE').notNull(),
    costNote: text(),
    location: text(),
    website: text(),
    phone: text(),
    schedule: text(),
    startsAt: timestamp({ precision: 3, mode: 'date' }),
    endsAt: timestamp({ precision: 3, mode: 'date' }),
    status: activityStatus().default('DRAFT').notNull(),
    highlight: boolean().default(false).notNull(),
    createdByUserId: text(),
    updatedByUserId: text(),
  },
  (table) => [
    index('Activity_endsAt_idx').using('btree', table.endsAt.asc().nullsLast()),
    index('Activity_status_category_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.category.asc().nullsLast(),
    ),
    index('Activity_status_highlight_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.highlight.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.createdByUserId],
      foreignColumns: [user.id],
      name: 'Activity_createdByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.updatedByUserId],
      foreignColumns: [user.id],
      name: 'Activity_updatedByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const systemConfig = pgTable('SystemConfig', {
  id: text().default('singleton').primaryKey().notNull(),
  updatedAt: timestamp({ precision: 3, mode: 'date' })
    .$defaultFn(() => new Date())
    .$onUpdateFn(() => new Date())
    .notNull(),
  pilotBaselineIncidentsPerMonth: doublePrecision(),
  pilotBaselineRelocationsPerMonth: doublePrecision(),
  pilotBaselineMediationHoursPerWeek: doublePrecision(),
  pilotStartDate: timestamp({ precision: 3, mode: 'date' }),
})

export const incident = pgTable(
  'Incident',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    placementId: text(),
    reportedById: text(),
    subjectId: text(),
    date: timestamp({ precision: 3, mode: 'date' }).notNull(),
    category: incidentCategory().default('INTERPERSONAL').notNull(),
    type: incidentType().notNull(),
    severity: incidentSeverity().notNull(),
    description: text().notNull(),
    resolution: text(),
    resolvedAt: timestamp({ precision: 3, mode: 'date' }),
    predictable: boolean(),
    compatibilityGap: text(),
    nextFollowUpDate: timestamp({ precision: 3, mode: 'date' }),
    followUpPriority: followUpPriority(),
    mediationMinutes: integer(),
    resolutionStage: resolutionStage().default('REPORTED').notNull(),
    stageEnteredAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('Incident_date_idx').using('btree', table.date.asc().nullsLast()),
    index('Incident_nextFollowUpDate_idx').using('btree', table.nextFollowUpDate.asc().nullsLast()),
    index('Incident_reportedById_idx').using('btree', table.reportedById.asc().nullsLast()),
    index('Incident_subjectId_idx').using('btree', table.subjectId.asc().nullsLast()),
    index('Incident_type_severity_idx').using(
      'btree',
      table.type.asc().nullsLast(),
      table.severity.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'Incident_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.placementId],
      foreignColumns: [placement.id],
      name: 'Incident_placementId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.reportedById],
      foreignColumns: [resident.id],
      name: 'Incident_reportedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.subjectId],
      foreignColumns: [resident.id],
      name: 'Incident_subjectId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const houseRule = pgTable(
  'HouseRule',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    scope: ruleScope().notNull(),
    housingUnitId: text(),
    key: text(),
    category: ruleCategory().notNull(),
    title: text().notNull(),
    body: text().notNull(),
    delegation: ruleDelegation().default('FIXED').notNull(),
    parentRuleId: text(),
    status: ruleStatus().default('ACTIVE').notNull(),
    version: integer().default(1).notNull(),
    effectiveFrom: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    effectiveUntil: timestamp({ precision: 3, mode: 'date' }),
    adoptedByProposalId: text(),
    createdByStaff: text(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('HouseRule_category_idx').using('btree', table.category.asc().nullsLast()),
    index('HouseRule_housingUnitId_status_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.status.asc().nullsLast(),
    ),
    uniqueIndex('HouseRule_key_key').using('btree', table.key.asc().nullsLast()),
    index('HouseRule_parentRuleId_idx').using('btree', table.parentRuleId.asc().nullsLast()),
    index('HouseRule_scope_status_idx').using(
      'btree',
      table.scope.asc().nullsLast(),
      table.status.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'HouseRule_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.parentRuleId],
      foreignColumns: [table.id],
      name: 'HouseRule_parentRuleId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.adoptedByProposalId],
      // Cast breaks the type-level cycle (HouseRule <-> Proposal reference
      // each other); the generated DDL is unchanged.
      foreignColumns: [proposal.id as AnyPgColumn],
      name: 'HouseRule_adoptedByProposalId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const proposal = pgTable(
  'Proposal',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    type: proposalType().notNull(),
    category: ruleCategory().notNull(),
    title: text().notNull(),
    body: text().notNull(),
    targetRuleId: text(),
    parentOrgRuleId: text(),
    proposedByResidentId: text(),
    proposedByStaff: text(),
    status: proposalStatus().default('DISCUSSION').notNull(),
    decisionMode: decisionMode().notNull(),
    threshold: voteThreshold().notNull(),
    quorumPercent: integer().notNull(),
    approvalPercent: integer().notNull(),
    eligibleVoterCount: integer().default(0).notNull(),
    discussionEndsAt: timestamp({ precision: 3, mode: 'date' }),
    votingOpenedAt: timestamp({ precision: 3, mode: 'date' }),
    votingEndsAt: timestamp({ precision: 3, mode: 'date' }),
    decidedAt: timestamp({ precision: 3, mode: 'date' }),
    outcomeSummary: text(),
    staffDecision: staffDecision(),
    staffNotes: text(),
    staffUserId: text(),
    staffDecidedAt: timestamp({ precision: 3, mode: 'date' }),
  },
  (table): PgTableExtraConfigValue[] => [
    index('Proposal_housingUnitId_status_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.status.asc().nullsLast(),
    ),
    index('Proposal_status_votingEndsAt_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.votingEndsAt.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'Proposal_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.targetRuleId],
      foreignColumns: [houseRule.id],
      name: 'Proposal_targetRuleId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.parentOrgRuleId],
      foreignColumns: [houseRule.id],
      name: 'Proposal_parentOrgRuleId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.proposedByResidentId],
      foreignColumns: [resident.id],
      name: 'Proposal_proposedByResidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const ruleAcknowledgement = pgTable(
  'RuleAcknowledgement',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    ruleId: text().notNull(),
    residentId: text().notNull(),
    ruleVersion: integer().notNull(),
    acknowledgedAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
  },
  (table) => [
    index('RuleAcknowledgement_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    uniqueIndex('RuleAcknowledgement_ruleId_residentId_ruleVersion_key').using(
      'btree',
      table.ruleId.asc().nullsLast(),
      table.residentId.asc().nullsLast(),
      table.ruleVersion.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.ruleId],
      foreignColumns: [houseRule.id],
      name: 'RuleAcknowledgement_ruleId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'RuleAcknowledgement_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const vote = pgTable(
  'Vote',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    proposalId: text().notNull(),
    residentId: text().notNull(),
    choice: voteChoice().notNull(),
    reason: text(),
    castAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
  },
  (table) => [
    uniqueIndex('Vote_proposalId_residentId_key').using(
      'btree',
      table.proposalId.asc().nullsLast(),
      table.residentId.asc().nullsLast(),
    ),
    index('Vote_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    foreignKey({
      columns: [table.proposalId],
      foreignColumns: [proposal.id],
      name: 'Vote_proposalId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'Vote_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const conflictAgreement = pgTable(
  'ConflictAgreement',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    incidentId: text().notNull(),
    terms: text().notNull(),
    mediatorName: text(),
    reviewDate: timestamp({ precision: 3, mode: 'date' }).notNull(),
    status: agreementStatus().default('PROPOSED').notNull(),
    outcomeNotes: text(),
    reviewedAt: timestamp({ precision: 3, mode: 'date' }),
    ruleProposalId: text(),
  },
  (table) => [
    index('ConflictAgreement_incidentId_idx').using('btree', table.incidentId.asc().nullsLast()),
    uniqueIndex('ConflictAgreement_ruleProposalId_key').using(
      'btree',
      table.ruleProposalId.asc().nullsLast(),
    ),
    index('ConflictAgreement_status_reviewDate_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.reviewDate.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.incidentId],
      foreignColumns: [incident.id],
      name: 'ConflictAgreement_incidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.ruleProposalId],
      foreignColumns: [proposal.id],
      name: 'ConflictAgreement_ruleProposalId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const agreementParty = pgTable(
  'AgreementParty',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    agreementId: text().notNull(),
    residentId: text().notNull(),
    acceptedAt: timestamp({ precision: 3, mode: 'date' }),
    declinedAt: timestamp({ precision: 3, mode: 'date' }),
  },
  (table) => [
    uniqueIndex('AgreementParty_agreementId_residentId_key').using(
      'btree',
      table.agreementId.asc().nullsLast(),
      table.residentId.asc().nullsLast(),
    ),
    index('AgreementParty_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    foreignKey({
      columns: [table.agreementId],
      foreignColumns: [conflictAgreement.id],
      name: 'AgreementParty_agreementId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'AgreementParty_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const residentPhoto = pgTable(
  'ResidentPhoto',
  {
    residentId: text().primaryKey().notNull(),
    data: bytea().notNull(),
    mimeType: text().notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'ResidentPhoto_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const expense = pgTable(
  'Expense',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    paidById: text().notNull(),
    createdById: text().notNull(),
    description: text().notNull(),
    category: text().notNull(),
    amountRappen: integer().notNull(),
    date: timestamp({ precision: 3, mode: 'date' }).notNull(),
  },
  (table) => [
    index('Expense_housingUnitId_date_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.date.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'Expense_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.paidById],
      foreignColumns: [resident.id],
      name: 'Expense_paidById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.createdById],
      foreignColumns: [resident.id],
      name: 'Expense_createdById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
  ],
)

export const expenseShare = pgTable(
  'ExpenseShare',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    expenseId: text().notNull(),
    residentId: text().notNull(),
    amountRappen: integer().notNull(),
  },
  (table) => [
    uniqueIndex('ExpenseShare_expenseId_residentId_key').using(
      'btree',
      table.expenseId.asc().nullsLast(),
      table.residentId.asc().nullsLast(),
    ),
    index('ExpenseShare_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    foreignKey({
      columns: [table.expenseId],
      foreignColumns: [expense.id],
      name: 'ExpenseShare_expenseId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'ExpenseShare_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
  ],
)

export const settlement = pgTable(
  'Settlement',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    housingUnitId: text().notNull(),
    fromId: text().notNull(),
    toId: text().notNull(),
    amountRappen: integer().notNull(),
    note: text(),
  },
  (table) => [
    index('Settlement_housingUnitId_idx').using('btree', table.housingUnitId.asc().nullsLast()),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'Settlement_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.fromId],
      foreignColumns: [resident.id],
      name: 'Settlement_fromId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.toId],
      foreignColumns: [resident.id],
      name: 'Settlement_toId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
  ],
)

export const account = pgTable(
  'Account',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    email: text().notNull(),
    passwordHash: text(),
    emailVerifiedAt: timestamp({ precision: 3, mode: 'date' }),
    userId: text(),
    residentId: text(),
  },
  (table) => [
    uniqueIndex('Account_email_key').using('btree', table.email.asc().nullsLast()),
    index('Account_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    uniqueIndex('Account_residentId_key').using('btree', table.residentId.asc().nullsLast()),
    index('Account_userId_idx').using('btree', table.userId.asc().nullsLast()),
    uniqueIndex('Account_userId_key').using('btree', table.userId.asc().nullsLast()),
    foreignKey({
      columns: [table.userId],
      foreignColumns: [user.id],
      name: 'Account_userId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'Account_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const authToken = pgTable(
  'AuthToken',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    tokenHash: text().notNull(),
    purpose: authTokenPurpose().notNull(),
    expiresAt: timestamp({ precision: 3, mode: 'date' }).notNull(),
    usedAt: timestamp({ precision: 3, mode: 'date' }),
    accountId: text().notNull(),
  },
  (table) => [
    index('AuthToken_accountId_purpose_idx').using(
      'btree',
      table.accountId.asc().nullsLast(),
      table.purpose.asc().nullsLast(),
    ),
    uniqueIndex('AuthToken_tokenHash_key').using('btree', table.tokenHash.asc().nullsLast()),
    foreignKey({
      columns: [table.accountId],
      foreignColumns: [account.id],
      name: 'AuthToken_accountId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const taskCompletion = pgTable(
  'TaskCompletion',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    taskId: text().notNull(),
    completedById: text().notNull(),
    completedAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    notes: text(),
    durationMinutes: integer(),
    completedItems: text()
      .array()
      .default(sql`ARRAY[]::TEXT[]`),
  },
  (table) => [
    index('TaskCompletion_completedById_idx').using('btree', table.completedById.asc().nullsLast()),
    index('TaskCompletion_taskId_idx').using('btree', table.taskId.asc().nullsLast()),
    foreignKey({
      columns: [table.taskId],
      foreignColumns: [householdTask.id],
      name: 'TaskCompletion_taskId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.completedById],
      foreignColumns: [resident.id],
      name: 'TaskCompletion_completedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const learningRecord = pgTable(
  'LearningRecord',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    kind: learningKind().notNull(),
    title: text().notNull(),
    status: learningStatus().default('PLANNED').notNull(),
    languageCode: text(),
    cefrLevel: text(),
    provider: text(),
    category: text(),
    hours: integer(),
    startedAt: timestamp({ precision: 3, mode: 'date' }),
    completedAt: timestamp({ precision: 3, mode: 'date' }),
    notes: text(),
    recordedBy: residentOrStaff().notNull(),
  },
  (table) => [
    index('LearningRecord_languageCode_cefrLevel_idx').using(
      'btree',
      table.languageCode.asc().nullsLast(),
      table.cefrLevel.asc().nullsLast(),
    ),
    index('LearningRecord_residentId_kind_idx').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.kind.asc().nullsLast(),
    ),
    index('LearningRecord_status_idx').using('btree', table.status.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'LearningRecord_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const messageThread = pgTable(
  'MessageThread',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    residentId: text().notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
  },
  (table) => [
    uniqueIndex('MessageThread_residentId_key').using('btree', table.residentId.asc().nullsLast()),
    index('MessageThread_updatedAt_idx').using('btree', table.updatedAt.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'MessageThread_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const message = pgTable(
  'Message',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    threadId: text().notNull(),
    authorResidentId: text(),
    authorUserId: text(),
    body: text().notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    readAt: timestamp({ precision: 3, mode: 'date' }),
  },
  (table) => [
    index('Message_threadId_createdAt_idx').using(
      'btree',
      table.threadId.asc().nullsLast(),
      table.createdAt.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.threadId],
      foreignColumns: [messageThread.id],
      name: 'Message_threadId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.authorResidentId],
      foreignColumns: [resident.id],
      name: 'Message_authorResidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.authorUserId],
      foreignColumns: [user.id],
      name: 'Message_authorUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    check(
      'Message_one_author',
      sql`("authorResidentId" IS NOT NULL) <> ("authorUserId" IS NOT NULL)`,
    ),
  ],
)

export const careAssignment = pgTable(
  'CareAssignment',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    staffId: text().notNull(),
    role: careRole().notNull(),
  },
  (table) => [
    uniqueIndex('CareAssignment_residentId_role_key').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.role.asc().nullsLast(),
    ),
    index('CareAssignment_staffId_idx').using('btree', table.staffId.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'CareAssignment_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.staffId],
      foreignColumns: [user.id],
      name: 'CareAssignment_staffId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
  ],
)

export const careAttribute = pgTable(
  'CareAttribute',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    domain: careRole().notNull(),
    key: text().notNull(),
    value: text().notNull(),
    updatedById: text().notNull(),
  },
  (table) => [
    index('CareAttribute_residentId_domain_idx').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.domain.asc().nullsLast(),
    ),
    uniqueIndex('CareAttribute_residentId_domain_key_key').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.domain.asc().nullsLast(),
      table.key.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'CareAttribute_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.updatedById],
      foreignColumns: [user.id],
      name: 'CareAttribute_updatedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
  ],
)

export const houseEvent = pgTable(
  'HouseEvent',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    title: text().notNull(),
    description: text().notNull(),
    category: houseEventCategory().default('SOCIAL').notNull(),
    location: text(),
    startsAt: timestamp({ precision: 3, mode: 'date' }).notNull(),
    endsAt: timestamp({ precision: 3, mode: 'date' }),
    status: houseEventStatus().default('PUBLISHED').notNull(),
    createdByStaffId: text(),
    createdByResidentId: text(),
  },
  (table) => [
    index('HouseEvent_housingUnitId_startsAt_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.startsAt.asc().nullsLast(),
    ),
    index('HouseEvent_status_startsAt_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.startsAt.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'HouseEvent_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.createdByStaffId],
      foreignColumns: [user.id],
      name: 'HouseEvent_createdByStaffId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.createdByResidentId],
      foreignColumns: [resident.id],
      name: 'HouseEvent_createdByResidentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const appointment = pgTable(
  'Appointment',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    staffId: text(),
    domain: careRole().notNull(),
    title: text().notNull(),
    startsAt: timestamp({ precision: 3, mode: 'date' }).notNull(),
    endsAt: timestamp({ precision: 3, mode: 'date' }),
    location: text(),
    notes: text(),
    status: appointmentStatus().default('SCHEDULED').notNull(),
    residentNote: text(),
    staffNote: text(),
  },
  (table) => [
    index('Appointment_residentId_startsAt_idx').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.startsAt.asc().nullsLast(),
    ),
    index('Appointment_staffId_startsAt_idx').using(
      'btree',
      table.staffId.asc().nullsLast(),
      table.startsAt.asc().nullsLast(),
    ),
    index('Appointment_status_domain_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.domain.asc().nullsLast(),
    ),
    index('Appointment_status_idx').using('btree', table.status.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'Appointment_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.staffId],
      foreignColumns: [user.id],
      name: 'Appointment_staffId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
  ],
)

export const eventRsvp = pgTable(
  'EventRsvp',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    eventId: text().notNull(),
    residentId: text().notNull(),
    status: eventRsvpStatus().default('GOING').notNull(),
  },
  (table) => [
    index('EventRsvp_eventId_idx').using('btree', table.eventId.asc().nullsLast()),
    uniqueIndex('EventRsvp_eventId_residentId_key').using(
      'btree',
      table.eventId.asc().nullsLast(),
      table.residentId.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.eventId],
      foreignColumns: [houseEvent.id],
      name: 'EventRsvp_eventId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'EventRsvp_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

export const opportunity = pgTable(
  'Opportunity',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    kind: opportunityKind().notNull(),
    title: text().notNull(),
    description: text().notNull(),
    organisation: text().notNull(),
    location: text(),
    schedule: text(),
    hoursPerWeek: integer(),
    seats: integer(),
    germanLevel: text(),
    permitRequirement: permitRequirement().default('NONE').notNull(),
    requirementNote: text(),
    contactName: text(),
    contactEmail: text(),
    contactPhone: text(),
    website: text(),
    status: opportunityStatus().default('DRAFT').notNull(),
    startsAt: timestamp({ precision: 3, mode: 'date' }),
    endsAt: timestamp({ precision: 3, mode: 'date' }),
    createdByUserId: text(),
    updatedByUserId: text(),
  },
  (table) => [
    index('Opportunity_endsAt_idx').using('btree', table.endsAt.asc().nullsLast()),
    index('Opportunity_status_kind_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.kind.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.createdByUserId],
      foreignColumns: [user.id],
      name: 'Opportunity_createdByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.updatedByUserId],
      foreignColumns: [user.id],
      name: 'Opportunity_updatedByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const opportunityApplication = pgTable(
  'OpportunityApplication',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    opportunityId: text().notNull(),
    stage: applicationStage().default('INTERESTED').notNull(),
    stageChangedAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    note: text(),
    createdBy: residentOrStaff().notNull(),
    supportedByUserId: text(),
    learningRecordId: text(),
  },
  (table) => [
    uniqueIndex('OpportunityApplication_learningRecordId_key').using(
      'btree',
      table.learningRecordId.asc().nullsLast(),
    ),
    index('OpportunityApplication_opportunityId_stage_idx').using(
      'btree',
      table.opportunityId.asc().nullsLast(),
      table.stage.asc().nullsLast(),
    ),
    index('OpportunityApplication_residentId_idx').using(
      'btree',
      table.residentId.asc().nullsLast(),
    ),
    uniqueIndex('OpportunityApplication_residentId_opportunityId_key').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.opportunityId.asc().nullsLast(),
    ),
    index('OpportunityApplication_stage_idx').using('btree', table.stage.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'OpportunityApplication_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.opportunityId],
      foreignColumns: [opportunity.id],
      name: 'OpportunityApplication_opportunityId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('restrict'),
    foreignKey({
      columns: [table.supportedByUserId],
      foreignColumns: [user.id],
      name: 'OpportunityApplication_supportedByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.learningRecordId],
      foreignColumns: [learningRecord.id],
      name: 'OpportunityApplication_learningRecordId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const marketplacePost = pgTable(
  'MarketplacePost',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    housingUnitId: text().notNull(),
    postedById: text().notNull(),
    title: text().notNull(),
    description: text().notNull(),
    kind: marketplacePostKind().notNull(),
    category: text().default('OTHER').notNull(),
    status: marketplacePostStatus().default('OPEN').notNull(),
    claimedById: text(),
    closedAt: timestamp({ precision: 3, mode: 'date' }),
    hiddenByStaff: boolean().default(false).notNull(),
    hiddenReason: text(),
    contactNote: text(),
    claimedAt: timestamp({ precision: 3, mode: 'date' }),
  },
  (table) => [
    index('MarketplacePost_housingUnitId_status_idx').using(
      'btree',
      table.housingUnitId.asc().nullsLast(),
      table.status.asc().nullsLast(),
    ),
    index('MarketplacePost_postedById_idx').using('btree', table.postedById.asc().nullsLast()),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'MarketplacePost_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.postedById],
      foreignColumns: [resident.id],
      name: 'MarketplacePost_postedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.claimedById],
      foreignColumns: [resident.id],
      name: 'MarketplacePost_claimedById_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const complaint = pgTable(
  'Complaint',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text(),
    subject: complaintSubject().notNull(),
    body: text().notNull(),
    status: complaintStatus().default('OPEN').notNull(),
    response: text(),
    respondedAt: timestamp({ precision: 3, mode: 'date' }),
    respondedByUserId: text(),
  },
  (table) => [
    index('Complaint_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('Complaint_residentId_idx').using('btree', table.residentId.asc().nullsLast()),
    index('Complaint_status_idx').using('btree', table.status.asc().nullsLast()),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'Complaint_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
    foreignKey({
      columns: [table.respondedByUserId],
      foreignColumns: [user.id],
      name: 'Complaint_respondedByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const residentDocument = pgTable(
  'ResidentDocument',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp({ precision: 3, mode: 'date' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date())
      .notNull(),
    residentId: text().notNull(),
    category: text().default('OTHER').notNull(),
    title: text().notNull(),
    fileName: text().notNull(),
    mimeType: text().notNull(),
    sizeBytes: integer().notNull(),
    uploadedByUserId: text(),
  },
  (table) => [
    index('ResidentDocument_residentId_createdAt_idx').using(
      'btree',
      table.residentId.asc().nullsLast(),
      table.createdAt.asc().nullsLast(),
    ),
    foreignKey({
      columns: [table.residentId],
      foreignColumns: [resident.id],
      name: 'ResidentDocument_residentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.uploadedByUserId],
      foreignColumns: [user.id],
      name: 'ResidentDocument_uploadedByUserId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('set null'),
  ],
)

export const residentDocumentBlob = pgTable(
  'ResidentDocumentBlob',
  {
    documentId: text().primaryKey().notNull(),
    data: bytea().notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.documentId],
      foreignColumns: [residentDocument.id],
      name: 'ResidentDocumentBlob_documentId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)

/**
 * Which PLACES a staff member is responsible for — the join behind
 * `User.siteAccess = 'ASSIGNED_UNITS'`. A join, not a String[] of unit ids on
 * User: a unit that closes must take its access rows with it. Cascade both
 * ways — pure access wiring, no history worth keeping once either side is
 * gone.
 */
export const staffUnit = pgTable(
  'StaffUnit',
  {
    id: text().primaryKey().$defaultFn(createId).notNull(),
    createdAt: timestamp({ precision: 3, mode: 'date' })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    staffId: text().notNull(),
    housingUnitId: text().notNull(),
  },
  (table) => [
    uniqueIndex('StaffUnit_staffId_housingUnitId_key').using(
      'btree',
      table.staffId.asc().nullsLast(),
      table.housingUnitId.asc().nullsLast(),
    ),
    index('StaffUnit_housingUnitId_idx').using('btree', table.housingUnitId.asc().nullsLast()),
    foreignKey({
      columns: [table.staffId],
      foreignColumns: [user.id],
      name: 'StaffUnit_staffId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
    foreignKey({
      columns: [table.housingUnitId],
      foreignColumns: [housingUnit.id],
      name: 'StaffUnit_housingUnitId_fkey',
    })
      .onUpdate('cascade')
      .onDelete('cascade'),
  ],
)
