/**
 * Staff dashboard labels
 */

export const DASHBOARD_LABELS = {
  greetingMorning: 'Guten Morgen',
  greetingDay: 'Guten Tag',
  greetingEvening: 'Guten Abend',

  today: 'heute',
  yesterday: 'gestern',
  daysAgo: 'Tagen',

  allClearSummary: 'Alles unter Kontrolle heute.',
  oneTaskWaiting: '1 Aufgabe wartet auf Sie.',
  tasksWaitingSuffix: 'Aufgaben warten auf Sie.',

  sectionOpenTasks: 'Offene Aufgaben',
  sectionDueSoon: 'Bald fällig',
  sectionQuickActions: 'Schnellaktionen',
  sectionTasks: 'Aufgaben',
  sectionOccupancy: 'Belegung',
  sectionHousing: 'Unterkünfte',

  statFreeBeds: 'Freie Plätze',
  statCheckIns: 'Check-ins',
  statOverdueSuffix: 'überfällig',
  statCurrentSuffix: 'aktuell',
  statHarmony: 'Harmonie',
  statDaysSuffix: 'Tage',
  statNoConflicts: 'ohne Konflikte',
  statMaintenance: 'Wartung',
  statOpenSuffix: 'offen',

  tileCheckIns: 'Check-ins durchführen',
  tilePlaceResidents: 'Bewohner platzieren',
  tileConflictUnits: 'Einheiten mit Konflikten',
  tileConflictUnitsDesc: 'Wiederholte Vorfälle in den letzten 30 Tagen',
  tileCheckInsThisWeek: 'Check-ins diese Woche',
  tilePlanProactively: 'Proaktiv planen',
  tileWaitingLongestSuffix: 'wartet am längsten',
  tileSincePrefix: 'Seit',
  tileIncidents: 'Vorfälle',

  dueTodayPrefix: 'Heute fällig',
  dueTomorrowPrefix: 'Morgen fällig',
  dueInPrefix: 'In',
  dueInSuffix: 'Tagen',

  showAllPrefix: 'Alle',
  showAllSuffix: 'anzeigen',
  showMoreSuffix: 'weitere',
  showAllLink: 'Alle',

  allClearTitle: 'Alles unter Kontrolle!',
  allClearAllDone: 'Alles erledigt!',
  allClearConflictFreeSuffix: 'Tage ohne Konflikte.',
  allClearBedsReadySuffix: 'Plätze für neue Bewohner bereit.',
  allClearAllOccupied: 'Alle Plätze belegt.',
  allClearNoDringend: 'Keine dringenden Aufgaben',
  allClearBedsFreeSuffix: 'Plätze frei',

  actionNewResident: 'Neuer Bewohner',
  actionNewUnit: 'Neue Einheit',
  actionStartMatching: 'Matching starten',
  actionReportIncident: 'Vorfall melden',
  actionMaintenanceTicket: 'Wartungsticket',
  actionCreateResident: 'Neuen Bewohner erfassen',
  actionViewStats: 'Statistiken ansehen',

  heroCriticalIncidentsSuffix: 'kritische Vorfälle',
  heroActionNow: 'Sofort bearbeiten',
  heroCheckInUrgentPrefix: 'Check-in dringend:',
  heroNotSeenSuffix: 'Tagen nicht gesehen',
  heroStartCheckIn: 'Check-in starten',
  heroPlaceResidentsSuffix: 'Bewohner platzieren',
  heroFreeBedsAvailableSuffix: 'freie Plätze verfügbar',
  heroOpenConflictsSuffix: 'offene Konflikte',
  heroMainProblemPrefix: 'Hauptproblem:',
  heroAnalyze: 'Analysieren',
  heroCheckInsPendingSuffix: 'Check-ins anstehend',
  heroNextPrefix: 'Nächster:',
  heroMonitorUnitsSuffix: 'Einheiten beobachten',
  heroHadSuffix: 'hatte',
  heroIncidentsSuffix: 'Vorfälle',
  heroReview: 'Überprüfen',

  alertCriticalAttentionSuffix: 'kritische Vorfälle erfordern sofortige Aufmerksamkeit',
  alertEdit: 'Bearbeiten',

  occupancyOccupied: 'belegt',
  occupancyOf: 'von',
  occupancyPlaces: 'Plätzen',
  occupancyFree: 'frei',
  occupancyAvailable: 'Verfügbar',
  occupancyFull: 'Voll belegt',
  occupancyMaintenance: 'In Wartung',
  occupancyClosed: 'Geschlossen',
  occupancyViewAll: 'Alle Unterkünfte',

  taskCriticalOpenSuffix: 'kritische Vorfälle offen',
  taskNoCritical: 'Keine kritischen Vorfälle',
  taskCheckInsOverdueSuffix: 'Check-ins überfällig',
  taskAllCheckInsCurrent: 'Alle Check-ins aktuell',
  taskWaitingPlacementSuffix: 'Bewohner warten auf Platzierung',
  taskAllPlaced: 'Alle Bewohner platziert',
  taskMaintenanceOverdueSuffix: 'Wartungstickets überfällig',
  taskMaintenanceCurrent: 'Wartung aktuell',
  taskWeek: 'Woche',
  taskDaysAgoPrefix: 'Vor',
  taskSincePrefix: 'Seit',

  // Analytics / placement stat cards
  analyticsOccupancyRate: 'Belegungsrate',
  analyticsOverdueCheckIns: 'Überfällige Check-ins',
  analyticsConflictEnded: 'Konfliktbedingt beendet',
  analyticsAvgSatisfaction: 'Ø Zufriedenheit',
  // Analytics page
  analyticsPageSubtitle: 'Übersicht über Belegung, Check-ins und Konflikte',
  analyticsConflictsTitle: (days: number) => `Konflikte (${days} Tage)`,
  analyticsUnresolved: (count: number) => `${count} ungelöst`,
  analyticsEndReasonsTitle: 'Beendigungsgründe (gesamt)',
  analyticsNoEndedPlacements: 'Keine beendeten Platzierungen',
} as const

export const MISSION_KPI_LABELS = {
  conflictsPerMonth: 'Konflikte / Monat',
  relocationsPerMonth: 'Umsiedlungen / Monat',
  conflictsMonthlyChart: 'Konflikte pro Monat',
  relocationsMonthlyChart: 'Konflikt-Umsiedlungen pro Monat',
  currentLabel: 'Dieser Monat',
  daysUnit: 'Tage',
  avgPlacementTime: 'Ø Platzierungszeit',
  last30Days: 'Letzte 30 Tage',
  targetDays: '≤ 2 Tage',
  conflictTrend: 'Konflikt-Trend',
  mediationHoursPerWeek: 'Mediationsstunden / Woche',
  mediationMonthlyChart: 'Mediationszeit pro Monat',
  hoursUnit: 'Std.',
  sectionTitle: 'Missions-KPIs',
  sectionDesc: (months: number) => `Letzte ${months} Monate — Ziel: weniger Konflikte, schnellere Platzierung`,
  trendImproving: 'Verbesserung',
  trendStable: 'Stabil',
  trendWorsening: 'Verschlechterung',
} as const

export const MAINTENANCE_CARD_LABELS = {
  newTicket: 'Neues Ticket',
} as const

export const ALGORITHM_ACCURACY_LABELS = {
  sectionTitle: 'Algorithmus-Genauigkeit',
  empty: 'Noch keine beendeten Platzierungen mit Kompatibilitätsbewertung vorhanden.',
  subtitle: (count: number) => `Vergleich: Kompatibilitätsbewertung vs. tatsächliches Ergebnis (${count} Platzierungen)`,
  avgScoreConflict: 'Ø Score bei Konflikt-Ende',
  avgScoreSuccess: 'Ø Score bei erfolgreichem Ende',
  resultsByTierTitle: 'Ergebnisse nach Kompatibilitätsstufe',
  placementsLabel: 'Platzierungen',
  conflictsLabel: 'Konflikte',
  satisfactionLabel: 'Zufriedenheit',
  avgDurationLabel: 'Ø Dauer',
  colTier: 'Stufe',
  colConflictRate: 'Konfliktrate',
  colAvgSatisfaction: 'Ø Zufriedenheit',
  colAvgDuration: 'Ø Dauer (Tage)',
  satisfactionByTierTitle: 'Zufriedenheit nach Kompatibilitätsstufe',
  checkInsLabel: 'Check-ins',
  predictionTitle: 'Vorhersage-Genauigkeit',
  predictableConflicts: 'Vorhersagbare Konflikte',
  unpredictable: 'Unvorhersagbare',
  notRated: 'Noch nicht bewertet',
  // DashboardMetrics
  statResidents: 'Bewohner',
  statWaitingForPlacement: (count: number) => `${count} warten auf Platzierung`,
  statAllPlaced: 'Alle platziert',
  statOfTotal: (total: number) => `von ${total} total`,
  statActivePlacements: (count: number) => `von ${count} aktiven Platzierungen`,
  statOpenIncidents: 'Offene Vorfälle',
  statConflictsMaintenance: (conflicts: number, maintenance: number) => `${conflicts} Konflikte, ${maintenance} Wartung`,
  // ConflictCard
  conflictCardTitle: 'Konflikte',
  conflictCardActiveSuffix: 'aktiv (30 Tage)',
  conflictCardOldest: (days: number) => `Ältester: ${days} Tage ungelöst`,
  conflictCardHotspots: 'Brennpunkte',
  conflictCardOccupied: 'belegt',
  conflictCardConflictCount: (count: number) => `${count} Konflikte`,
  conflictCardLast7Days: 'Letzte 7 Tage',
  conflictCardNoneNew: '✓ Keine neuen',
  conflictCardNewCount: (count: number) => `${count} neue`,
  conflictCardAllClear: 'Keine aktiven Konflikte',
  conflictCardViewAll: 'Alle Vorfälle →',
  // RecentPlacementsTable
  checkInOverdueBadge: 'Check-in überfällig',
  checkInPendingBadge: 'Check-in ausstehend',
  tableOverdue: 'Überfällig',
  tablePending: 'Ausstehend',
  tableColDate: 'Datum',
  tableColResident: 'Bewohner',
  tableColUnit: 'Unterkunft',
  tableColLastCheckIn: 'Letzter Check-in',
  tableColStatus: 'Status',
  // ConflictAnalysisSection
  conflictCausesTitle: 'Konfliktursachen',
  conflictCausesEmpty: 'Noch keine detaillierten Konfliktdaten erfasst.',
  conflictCausesEmptyHint: 'Bei zukünftigen Konfliktbeendigungen werden Ursachen dokumentiert.',
  algorithmInsightsTitle: 'Algorithmus-Einsichten',
  predictabilityEmpty: 'Noch keine Vorhersagbarkeits-Daten erfasst.',
  predictableLabel: 'Vorhersehbar',
  unpredictableLabel: 'Nicht vorhersehbar',
  predictabilityRateSuffix: 'der Konflikte waren laut Fallarbeitern vorhersehbar.',
  lowScoreWarningPrefix: 'Konflikte hatten einen Kompatibilitäts-Score unter 60% bei Platzierung.',
  lowScoreHint: '→ Erwägen Sie höhere Schwellenwerte für Platzierungen',
} as const
