/**
 * Staff dashboard labels
 */

export const DASHBOARD_LABELS = {
  greetingMorning: 'Guten Morgen',
  greetingDay: 'Guten Tag',
  greetingEvening: 'Guten Abend',

  today: 'heute',
  yesterday: 'gestern',
  daysAgo: 'Tagen',

  allClearSummary: 'Alles unter Kontrolle heute.',
  oneTaskWaiting: '1 Aufgabe wartet auf Sie.',
  tasksWaitingSuffix: 'Aufgaben warten auf Sie.',

  sectionOpenTasks: 'Offene Aufgaben',
  sectionDueSoon: 'Bald fällig',
  sectionQuickActions: 'Schnellaktionen',
  sectionTasks: 'Aufgaben',
  sectionOccupancy: 'Belegung',
  sectionHousing: 'Unterkünfte',

  statFreeBeds: 'Freie Plätze',
  statCheckIns: 'Check-ins',
  statOverdueSuffix: 'überfällig',
  statCurrentSuffix: 'aktuell',
  statHarmony: 'Harmonie',
  statDaysSuffix: 'Tage',
  statNoConflicts: 'ohne Konflikte',
  statMaintenance: 'Wartung',
  statOpenSuffix: 'offen',

  tileCheckIns: 'Check-ins durchführen',
  tilePlaceResidents: 'Bewohner platzieren',
  tileWaitingForPlacement: 'Warten auf Wohnplatz',
  tileConflictUnits: 'Einheiten mit Konflikten',
  tileConflictUnitsDesc: 'Wiederholte Vorfälle in den letzten 30 Tagen',
  tileCheckInsThisWeek: 'Check-ins diese Woche',
  tilePlanProactively: 'Proaktiv planen',
  tileWaitingLongestSuffix: 'wartet am längsten',
  tileSincePrefix: 'Seit',
  tileIncidents: 'Vorfälle',

  dueTodayPrefix: 'Heute fällig',
  dueTomorrowPrefix: 'Morgen fällig',
  dueInPrefix: 'In',
  dueInSuffix: 'Tagen',

  showAllPrefix: 'Alle',
  showAllSuffix: 'anzeigen',
  showMoreSuffix: 'weitere',
  showAllLink: 'Alle',

  allClearTitle: 'Alles unter Kontrolle!',
  allClearAllDone: 'Alles erledigt!',
  allClearConflictFreeSuffix: 'Tage ohne Konflikte.',
  allClearBedsReadySuffix: 'Plätze für neue Bewohner bereit.',
  allClearAllOccupied: 'Alle Plätze belegt.',
  allClearNoDringend: 'Keine dringenden Aufgaben',
  allClearBedsFreeSuffix: 'Plätze frei',

  actionNewResident: 'Neuer Bewohner',
  actionNewUnit: 'Neue Einheit',
  actionStartMatching: 'Matching starten',
  actionReportIncident: 'Vorfall melden',
  actionMaintenanceTicket: 'Wartungsticket',
  actionCreateResident: 'Neuen Bewohner erfassen',
  actionViewStats: 'Statistiken ansehen',

  heroCriticalIncidentsSuffix: 'kritische Vorfälle',
  heroActionNow: 'Sofort bearbeiten',
  heroCheckInUrgentPrefix: 'Check-in dringend:',
  heroNotSeenSuffix: 'Tagen nicht gesehen',
  heroStartCheckIn: 'Check-in starten',
  heroPlaceResidentsSuffix: 'Bewohner platzieren',
  heroFreeBedsAvailableSuffix: 'freie Plätze verfügbar',
  heroOpenConflictsSuffix: 'offene Konflikte',
  heroMainProblemPrefix: 'Hauptproblem:',
  heroAnalyze: 'Analysieren',
  heroCheckInsPendingSuffix: 'Check-ins anstehend',
  heroNextPrefix: 'Nächster:',
  heroMonitorUnitsSuffix: 'Einheiten beobachten',
  heroHadSuffix: 'hatte',
  heroIncidentsSuffix: 'Vorfälle',
  heroReview: 'Überprüfen',

  alertCriticalAttentionSuffix: 'kritische Vorfälle erfordern sofortige Aufmerksamkeit',
  alertEdit: 'Bearbeiten',

  occupancyOccupied: 'belegt',
  occupancyOf: 'von',
  occupancyPlaces: 'Plätzen',
  occupancyFree: 'frei',
  occupancyAvailable: 'Verfügbar',
  occupancyFull: 'Voll belegt',
  occupancyMaintenance: 'In Wartung',
  occupancyClosed: 'Geschlossen',
  occupancyViewAll: 'Alle Unterkünfte',

  taskCriticalOpenSuffix: 'kritische Vorfälle offen',
  taskNoCritical: 'Keine kritischen Vorfälle',
  taskCheckInsOverdueSuffix: 'Check-ins überfällig',
  taskAllCheckInsCurrent: 'Alle Check-ins aktuell',
  taskWaitingPlacementSuffix: 'Bewohner warten auf Platzierung',
  taskAllPlaced: 'Alle Bewohner platziert',
  taskMaintenanceOverdueSuffix: 'Wartungstickets überfällig',
  taskMaintenanceCurrent: 'Wartung aktuell',
  taskWeek: 'Woche',
  taskDaysAgoPrefix: 'Vor',
  taskSincePrefix: 'Seit',

  // Analytics / placement stat cards
  analyticsOccupancyRate: 'Belegungsrate',
  analyticsOverdueCheckIns: 'Überfällige Check-ins',
  analyticsConflictEnded: 'Konfliktbedingt beendet',
  analyticsAvgSatisfaction: 'Ø Zufriedenheit',
} as const

export const MISSION_KPI_LABELS = {
  conflictsPerMonth: 'Konflikte / Monat',
  relocationsPerMonth: 'Umsiedlungen / Monat',
  conflictsMonthlyChart: 'Konflikte pro Monat',
  relocationsMonthlyChart: 'Konflikt-Umsiedlungen pro Monat',
  currentLabel: 'Dieser Monat',
  daysUnit: 'Tage',
  avgPlacementTime: 'Ø Platzierungszeit',
  last30Days: 'Letzte 30 Tage',
  targetDays: '≤ 2 Tage',
  conflictTrend: 'Konflikt-Trend',
  sectionTitle: 'Missions-KPIs',
  sectionDesc: (months: number) => `Letzte ${months} Monate — Ziel: weniger Konflikte, schnellere Platzierung`,
  trendImproving: 'Verbesserung',
  trendStable: 'Stabil',
  trendWorsening: 'Verschlechterung',
} as const

export const MAINTENANCE_CARD_LABELS = {
  newTicket: 'Neues Ticket',
} as const
