export const EXPORT_LABELS = {
  exportButton: 'Exportieren',
  importButton: 'Importieren',
  downloadTemplate: 'Vorlage herunterladen',
  importing: 'Importiere...',
  preview: 'Vorschau',
  result: 'Ergebnis',
  created: 'erstellt',
  skipped: 'übersprungen',
  errors: 'Fehler',
  row: 'Zeile',
  noFile: 'Keine Datei hochgeladen',
  parseFailed: 'CSV-Parsing fehlgeschlagen',
  selectFile: 'CSV-Datei wählen',
} as const

/** Column headers for CSV export files — SSOT for all export German text */
export const EXPORT_COLUMN_HEADERS = {
  // Residents
  code: 'Code',
  status: 'Status',
  ageRange: 'Altersgruppe',
  gender: 'Geschlecht',
  familyStatus: 'Familienstatus',
  sleepSchedule: 'Schlafrhythmus',
  noiseTolerance: 'Lärmtoleranz',
  cleanlinessPractice: 'Eigene Ordnung',
  cleanlinessExpectation: 'Erwartung an andere',
  chaosTolerance: 'Toleranz für Unordnung',
  socialStyle: 'Sozialstil',
  smokingStatus: 'Raucherstatus',
  mobilityNeeds: 'Mobilitätsbedarf',
  supportLevel: 'Unterstützungsstufe',
  languages: 'Sprachen',
  createdAt: 'Erstellt am',
  // Incidents
  id: 'ID',
  date: 'Datum',
  category: 'Kategorie',
  type: 'Typ',
  severity: 'Schweregrad',
  description: 'Beschreibung',
  resolution: 'Lösung',
  resolvedAt: 'Gelöst am',
  // Placements
  startDate: 'Startdatum',
  endDate: 'Enddatum',
  endReason: 'Endgrund',
  compatibilityScore: 'Kompatibilität',
  satisfactionRating: 'Zufriedenheit',
  // Satisfaction
  checkInType: 'Typ',
  overallSatisfaction: 'Gesamtzufriedenheit',
  roommateRelations: 'Mitbewohner',
  facilitySatisfaction: 'Einrichtung',
  safetyFeeling: 'Sicherheit',
  concerns: 'Bedenken',
  improvements: 'Verbesserungen',
} as const
