/**
 * Matching and placement labels: UI text for matching workflow,
 * spot selection, unit mode, resident selector, and placement confirmation.
 */

export const MATCHING_LABELS = {
  topRecommendation: 'Top Empfehlung',
  topRank: (rank: number) => `Top ${rank}`,
  empty: 'Leer',
  history: 'Verlauf:',
  conflictFree: 'konfliktfrei)',
  perMonthAvg: '/Monat Ø',
  conflictsLast30Days: 'Konflikte letzte 30 Tage',
  apartmentProfile: 'Wohnungs-Profil',
  residents: 'Bewohner',
  matching: 'Passend',
  scoreDerivation: 'Score-Berechnung anzeigen',
  basePenalty: 'Basis: 100 Punkte',
  conflictDeductions: 'Abzüge (Konflikte):',
  strengthBonus: 'Bonus (Stärken):',
  smallGroupBonus: 'Bonus (kleine Gruppe):',
  totalFit: 'Gesamtpassung',
  historicalData: 'Historische Daten',
  placements: 'Platzierungen',
  successRate: 'Erfolgsrate',
  successRateDesc: (pct: number) => `waren erfolgreich`,
  placementsWithSimilar: 'Platzierungen mit ähnlicher Kompatibilität',
  noHistoricalData: 'Keine historischen Daten für ähnliche Kompatibilitätswerte',
  plusMinusTen: '±10',
  available: 'verfügbar',
  noRoommatesNoConflicts: 'Keine Mitbewohner - keine Konflikte',
  sharedLanguageWith: 'Gemeinsame Sprache mit',
  residentsCount: 'Bewohner(n)',
  currentResidents: 'Aktuelle Bewohner:',
  strengths: 'Stärken',
  concerns: 'Bedenken',
  challenges: 'Herausforderungen',
  moreConcerns: (count: number) => `+${count} weitere Bedenken`,
  blocked: 'Blockiert',
  place: 'Platzieren',
  placeLowCompat: 'Platzieren (niedrige Kompatibilität)',
  // Spot selection
  noSpotsAvailable: 'Keine freien Plätze verfügbar',
  selectSpot: 'Platz auswählen',
  noSuitableSpots: 'Keine Plätze für diesen Bewohner geeignet',
  medDocsMissing: '(med. Dokumente fehlen)',
  moreUnsuitableSpots: (count: number) => `${count} weitere Plätze (nicht geeignet)`,
  medDocsRequired: '(med. Dok. erforderlich)',
  notAuthorized: '(nicht berechtigt)',
  // Unit mode
  matchingResidents: 'Passende Bewohner',
  occupied: 'belegt',
  freeSpots: 'freie Plätze',
  back: 'Zurück',
  noMatchingResidents: 'Keine passenden unplatzierten Bewohner',
  createNewResident: 'Neuen Bewohner erfassen',
  // Resident selector
  unplacedResidents: 'Unplatzierte Bewohner',
  searchPlaceholder: 'Bewohner suchen (Code, Sprache)',
  search: 'Suchen',
  noResidentsFound: 'Keine Bewohner für diese Suche gefunden',
  selected: 'Ausgewählt',
  placedResidents: 'Platzierte Bewohner',
  selectForAnalysis: 'Wählen Sie einen Bewohner für "Was-wäre-wenn"-Analyse',
  placed: 'Platziert',
  compare: 'Vergleichen',
} as const

export const ALGORITHM_OVERVIEW_LABELS = {
  processStep1Title: 'Profil erfassen',
  processStep2Title: 'Kompatibilität berechnen',
  processStep3Title: 'Empfehlung erhalten',
  tabDimensions: 'Dimensionen',
  tabFactors: 'Faktoren',
  headToHeadAvg: 'Durchschnitt',
} as const

export const PLACEMENT_ACTIONS_LABELS = {
  actionsTitle: 'Aktionen',
  transferTitle: 'Bewohner verlegen',
  endTitle: 'Platzierung beenden',
  conflictAnalysisTitle: 'Konfliktanalyse',
  conflictAnalysisDesc: 'Diese Angaben helfen, das Matching zu verbessern und zukünftige Konflikte zu vermeiden.',
  conflictCauseLabel: 'Hauptursache des Konflikts *',
  conflictPredictableLabel: 'War der Konflikt vorhersehbar?',
  conflictAlgorithmLabel: 'Hätte der Algorithmus diesen Konflikt vorhersagen können?',
  linkedIncidentLabel: 'Verknüpfter Vorfall',
  noLinkedIncident: 'Keinen Vorfall verknüpfen',
  transferNotesLabel: 'Notizen',
  transferNotesPlaceholder: 'Optionale Anmerkungen zur Verlegung...',
  endNotesLabel: 'Notizen',
  endNotesPlaceholder: 'Optionale Anmerkungen...',
  endBtn: 'Platzierung endgültig beenden',
  conflictNoPredictable: 'Nein',
} as const

export const PLACEMENT_CONCERN_LABELS = {
  wheelchairRequired: 'Benötigt Rollstuhlzugang',
  groundFloorRequired: 'Benötigt Erdgeschoss',
  smokerInNonSmokingUnit: 'Raucher, aber Nichtraucher-Unterkunft',
} as const

export const PLACEMENT_CONFIRM_LABELS = {
  title: 'Platzierung bestätigen',
  prompt: 'Sie sind dabei zu platzieren:',
  resident: 'Bewohner:',
  unit: 'Unterkunft:',
  spot: 'Platz:',
  compatibility: 'Kompatibilität:',
  lowCompatWarning: 'Niedrige Kompatibilität',
  lowCompatMessage: 'Diese Platzierung hat eine niedrige Kompatibilitätsbewertung. Bitte stellen Sie sicher, dass dies die beste verfügbare Option ist.',
  notePoints: 'Beachten Sie folgende Punkte:',
  confirmMessage: 'Diese Aktion wird den Bewohner platzieren und den Platz als belegt markieren. Möchten Sie fortfahren?',
  cancel: 'Abbrechen',
  placing: 'Wird platziert...',
  confirm: 'Jetzt platzieren',
} as const
