/**
 * Matching and placement labels: UI text for matching workflow,
 * spot selection, unit mode, resident selector, and placement confirmation.
 */

export const MATCHING_LABELS = {
  topRecommendation: 'Top Empfehlung',
  topRank: (rank: number) => `Top ${rank}`,
  empty: 'Leer',
  history: 'Verlauf:',
  conflictFree: 'konfliktfrei)',
  perMonthAvg: '/Monat Ø',
  conflictsLast30Days: 'Konflikte letzte 30 Tage',
  apartmentProfile: 'Wohnungs-Profil',
  residents: 'Bewohner',
  matching: 'Passend',
  scoreDerivation: 'Score-Berechnung anzeigen',
  basePenalty: 'Basis: 100 Punkte',
  conflictDeductions: 'Abzüge (Konflikte):',
  strengthBonus: 'Bonus (Stärken):',
  smallGroupBonus: 'Bonus (kleine Gruppe):',
  totalFit: 'Gesamtpassung',
  historicalData: 'Historische Daten',
  placements: 'Platzierungen',
  successRate: 'Erfolgsrate',
  successRateDesc: (pct: number) => `waren erfolgreich`,
  placementsWithSimilar: 'Platzierungen mit ähnlicher Kompatibilität',
  noHistoricalData: 'Keine historischen Daten für ähnliche Kompatibilitätswerte',
  plusMinusTen: '±10',
  available: 'verfügbar',
  noRoommatesNoConflicts: 'Keine Mitbewohner - keine Konflikte',
  sharedLanguageWith: 'Gemeinsame Sprache mit',
  residentsCount: 'Bewohner(n)',
  currentResidents: 'Aktuelle Bewohner:',
  strengths: 'Stärken',
  concerns: 'Bedenken',
  challenges: 'Herausforderungen',
  moreConcerns: (count: number) => `+${count} weitere Bedenken`,
  blocked: 'Blockiert',
  place: 'Platzieren',
  placeLowCompat: 'Platzieren (niedrige Kompatibilität)',
  // Spot selection
  noSpotsAvailable: 'Keine freien Plätze verfügbar',
  selectSpot: 'Platz auswählen',
  noSuitableSpots: 'Keine Plätze für diesen Bewohner geeignet',
  medDocsMissing: '(med. Dokumente fehlen)',
  moreUnsuitableSpots: (count: number) => `${count} weitere Plätze (nicht geeignet)`,
  medDocsRequired: '(med. Dok. erforderlich)',
  notAuthorized: '(nicht berechtigt)',
  // Unit mode
  matchingResidents: 'Passende Bewohner',
  occupied: 'belegt',
  freeSpots: 'freie Plätze',
  back: 'Zurück',
  noMatchingResidents: 'Keine passenden unplatzierten Bewohner',
  createNewResident: 'Neuen Bewohner erfassen',
  // Resident selector
  unplacedResidents: 'Unplatzierte Bewohner',
  searchPlaceholder: 'Bewohner suchen (Code, Sprache)',
  search: 'Suchen',
  noResidentsFound: 'Keine Bewohner für diese Suche gefunden',
  selected: 'Ausgewählt',
  placedResidents: 'Platzierte Bewohner',
  selectForAnalysis: 'Wählen Sie einen Bewohner für "Was-wäre-wenn"-Analyse',
  placed: 'Platziert',
  compare: 'Vergleichen',
  // Matching page header
  findMatchingResidents: (address: string) => `Finden Sie passende Bewohner für ${address}`,
  step2SelectUnit: (code: string) => `Schritt 2 von 2: Wählen Sie eine Unterkunft für ${code}`,
  findOptimalPlacement: 'Finden Sie die optimale Platzierung für Bewohner',
  whoFitsIn: (code: string) => `Wer passt in ${code}?`,
  profileCaptured: 'Profil erfasst',
  findUnit: 'Unterkunft finden',
  residentCreated: (code: string) => `Bewohner ${code} erfolgreich erstellt`,
  newResidentBannerDesc: 'Wählen Sie jetzt eine passende Unterkunft. Die Unterkünfte sind nach Kompatibilität sortiert - oben die besten Matches.',
  selectResidentForMatches: 'Wählen Sie einen Bewohner aus, um Matches zu sehen',
} as const

export const ALGORITHM_OVERVIEW_LABELS = {
  processStep1Title: 'Profil erfassen',
  processStep2Title: 'Kompatibilität berechnen',
  processStep3Title: 'Empfehlung erhalten',
  tabDimensions: 'Dimensionen',
  tabFactors: 'Faktoren',
  tabOverview: 'Übersicht',
  tabScience: 'Forschung',
  tabCollection: 'Datenerfassung',
  tabTechnical: 'Technik',
  headToHeadAvg: 'Durchschnitt',
  heroSubtitle: 'Evidenzbasiertes Matching',
  heroTitle: 'Kompatibilitäts-Algorithmus',
  heroDesc: (factors: number, dimensions: number) =>
    `Basierend auf wissenschaftlicher Forschung zu Wohnkonflikten analysiert unser System ${factors} Faktoren in ${dimensions} Dimensionen für harmonisches Zusammenleben.`,
  sourcesLabel: (count: number) => `${count} Quellen`,
  ethicsValue: 'Ethisch',
  ethicsLabel: 'gestaltet',
  dimensionsIntro: 'Alle Faktoren werden direkt aus der Algorithmus-Konfiguration generiert. Klicken Sie auf eine Dimension für Details.',
  factorsCount: (n: number) => `${n} Faktoren`,
} as const

export const PLACEMENT_ACTIONS_LABELS = {
  actionsTitle: 'Aktionen',
  transferTitle: 'Bewohner verlegen',
  endTitle: 'Platzierung beenden',
  conflictAnalysisTitle: 'Konfliktanalyse',
  conflictAnalysisDesc: 'Diese Angaben helfen, das Matching zu verbessern und zukünftige Konflikte zu vermeiden.',
  conflictCauseLabel: 'Hauptursache des Konflikts *',
  conflictPredictableLabel: 'War der Konflikt vorhersehbar?',
  conflictAlgorithmLabel: 'Hätte der Algorithmus diesen Konflikt vorhersagen können?',
  linkedIncidentLabel: 'Verknüpfter Vorfall',
  noLinkedIncident: 'Keinen Vorfall verknüpfen',
  transferNotesLabel: 'Notizen',
  transferNotesPlaceholder: 'Optionale Anmerkungen zur Verlegung...',
  endNotesLabel: 'Notizen',
  endNotesPlaceholder: 'Optionale Anmerkungen...',
  endBtn: 'Platzierung endgültig beenden',
  conflictNoPredictable: 'Nein',
  // Button labels
  checkinBtn: 'Check-in durchführen',
  transferToggleBtn: 'Verlegen',
  endToggleBtn: 'Beenden',
  closeBtn: '✕ Schliessen',
  transferConfirmBtn: 'Verlegen bestätigen',
  // Hints
  shortcutHint: 'Schnellzugriff: Alt+Shift+V (Verlegen), Alt+Shift+E (Beenden)',
  noEligibleUnits: 'Aktuell gibt es keine geeigneten Ziel-Unterkünfte für diesen Bewohner. Prüfen Sie medizinische Berechtigung oder verfügbare Plätze.',
  // Transfer form
  targetUnitLabel: 'Ziel-Unterkunft *',
  targetSpotLabel: 'Ziel-Platz *',
  selectSpot: 'Platz auswählen',
  selectUnitFirst: 'Zuerst Unterkunft wählen',
  medDocsSpotHint: 'Zeigt Plätze passend zur med. Dokumentation',
  noMedDocsSpotHint: 'Zeigt nur Betten (keine med. Dokumentation)',
  transferReasonLabel: 'Grund für Verlegung *',
  transferReasonHint: 'Wählen Sie den Hauptgrund für die Verlegung',
  summaryLabel: 'Zusammenfassung:',
  // End form
  endWarningTitle: 'Achtung:',
  endWarning: 'Diese Aktion beendet die aktuelle Platzierung. Der Bewohner wird als nicht platziert markiert.',
  endReasonLabel: 'Grund *',
  conflictPredictableYes: 'Ja',
  conflictScoreHint: (score: number) => `(Score war ${score}%)`,
  incidentOptionalHint: 'Optional: Vorfall der zu dieser Beendigung geführt hat',
  // Dynamic summaries
  transferSummaryWithUnit: (unitCode: string) =>
    `Bewohner wird in ${unitCode} verlegt. Ziel-Unterkunft prüfen und Grund dokumentieren.`,
  transferSummaryEmpty: 'Wählen Sie eine Ziel-Unterkunft, um die Verlegung zu bestätigen.',
  endSummaryWithReason: (reason: string) =>
    `Diese Platzierung wird beendet (Grund: ${reason}). Bewohner wird als unplatziert geführt.`,
  endSummaryEmpty: 'Wählen Sie einen Grund, um die Beendigung zu bestätigen.',
} as const

export const PLACEMENT_CONCERN_LABELS = {
  wheelchairRequired: 'Benötigt Rollstuhlzugang',
  groundFloorRequired: 'Benötigt Erdgeschoss',
  smokerInNonSmokingUnit: 'Raucher, aber Nichtraucher-Unterkunft',
} as const

export const PLACEMENT_CONFIRM_LABELS = {
  title: 'Platzierung bestätigen',
  prompt: 'Sie sind dabei zu platzieren:',
  resident: 'Bewohner:',
  unit: 'Unterkunft:',
  spot: 'Platz:',
  compatibility: 'Kompatibilität:',
  lowCompatWarning: 'Niedrige Kompatibilität',
  lowCompatMessage: 'Diese Platzierung hat eine niedrige Kompatibilitätsbewertung. Bitte stellen Sie sicher, dass dies die beste verfügbare Option ist.',
  notePoints: 'Beachten Sie folgende Punkte:',
  confirmMessage: 'Diese Aktion wird den Bewohner platzieren und den Platz als belegt markieren. Möchten Sie fortfahren?',
  cancel: 'Abbrechen',
  placing: 'Wird platziert...',
  confirm: 'Jetzt platzieren',
} as const
