/**
 * Portal labels: resident-facing UI text
 */
import { ORG_CONTACT, ORG_CONTACT_CHANNELS } from '@/lib/config/organization'
import { RESIDENT_CODE_PREFIX } from '@/lib/auth/code-prefixes'

/** One sentence naming the real channels — reused wherever a page dead-ends. */
const CONTACT_FALLBACK_SENTENCE = `Melde dich bei deiner Betreuungsperson — bei Schäden: ${ORG_CONTACT.maintenancePhone} (${ORG_CONTACT.maintenanceHours}) oder ${ORG_CONTACT.maintenanceEmail}.`

export const PORTAL_LABELS = {
  title: 'Mein Zuhause',
  nav: {
    overview: 'Übersicht',
    apartment: 'Wohnung',
    expenses: 'Ausgaben',
    roommates: 'Mitbewohner',
    chores: 'Aufgaben',
    rules: 'Regeln',
    decisions: 'Abstimmen',
    report: 'Melden',
    messages: 'Nachrichten',
    learning: 'Lernen',
    housing: 'Unterkünfte',
    activities: 'Aktivitäten',
    marketplace: 'Marktplatz',
    events: 'Veranstaltungen',
    preferences: 'Einstellungen',
    profile: 'Profil',
    reports: 'Meine Meldungen',
    transfer: 'Verlegung',
    help: 'Hilfe',
    logout: 'Abmelden',
    more: 'Mehr',
    moreTitle: 'Alles im Überblick',
    closeMore: 'Menü schliessen',
  },
  /**
   * Headings for the sections of the "Mehr" sheet. Named for what a resident
   * wants, not for the tables behind them — somebody looking for the cleaning
   * rota thinks "Alltag", never "Chores".
   */
  /**
   * The page that answers "what happened to the thing I reported?".
   *
   * It exists because that question had no answer: the list lived only as a
   * preview on the dashboard, the nav entry led to the submission form, and
   * anything past the fifth report could not be reached from anywhere.
   */
  reports: {
    title: 'Deine Meldungen',
    subtitle: 'Alles, was du gemeldet hast — und was die Betreuung dazu sagt.',
    showAll: 'Alle Meldungen anzeigen',
    showAllCount: 'Alle Meldungen anzeigen',
    empty: 'Du hast noch nichts gemeldet.',
    emptyAction: 'Problem melden',
    backToOverview: 'Zur Übersicht',
    openSection: 'Offen',
    doneSection: 'Erledigt',
    /** Shown on the confirmation screen, so the report is one tap away. */
    viewYours: 'Deine Meldungen ansehen',
  },
  emergency: 'Bei Notfällen: 112 oder Hausverwaltung kontaktieren',
  pages: {
    dashboard: 'Willkommen',
    dashboardSubtitle: 'Hier findest du alles zu deiner Unterkunft',
    roommates: 'Deine Mitbewohner',
    rules: 'Hausregeln',
    decisions: 'Beschlüsse im Haus',
    report: 'Problem melden',
    reportSubtitle: 'Melde technische Probleme oder Konflikte',
    preferences: 'Deine Einstellungen',
    preferencesSubtitle: 'Diese Angaben helfen uns, passende Mitbewohner zu finden',
    help: 'Hilfe & FAQ',
    helpSubtitle: 'Antworten auf häufig gestellte Fragen und Kontaktinformationen',
    housing: 'Verfügbare Unterkünfte',
    housingSubtitle: 'Unterkünfte, die zu deinen Einstellungen passen',
    activities: 'Aktivitäten in Zürich',
    activitiesSubtitle: 'Kostenlose und günstige Angebote für dich in der Region',
  },
  activities: {
    allCategories: 'Alle Kategorien',
    showAll: 'Alle Aktivitäten anzeigen',
    costFree: 'Kostenlos',
    costReduced: 'Ermässigt',
    costPaid: 'Kostenpflichtig',
    website: 'Website öffnen',
    phone: 'Anrufen',
    noResults: 'Keine Aktivitäten in dieser Kategorie gefunden.',
    dashboardTitle: 'Aktivitäten in Zürich',
    dashboardSubtitle: 'Kostenlose & günstige Angebote',
    dashboardCta: 'Alle Angebote anzeigen',
  },
  form: {
    submit: 'Absenden',
    submitting: 'Wird gesendet...',
    saving: 'Wird gespeichert...',
    saved: 'Gespeichert',
    cancel: 'Abbrechen',
    back: '← Zurück zur Übersicht',
    errorGeneric: 'Ein Fehler ist aufgetreten. Bitte erneut versuchen.',
    successGeneric: 'Erfolgreich gespeichert',
  },
  login: {
    title: 'Mein Zuhause',
    subtitle: 'Gib deinen Bewohnercode ein, um fortzufahren',
    placeholder: `Dein Code (z.B. ${RESIDENT_CODE_PREFIX}001)`,
    submit: 'Einloggen',
    hint: 'Deinen Code findest du auf deinem Willkommensbrief',
    errors: {
      code_required: 'Bitte Code eingeben',
      invalid_code: 'Code nicht gefunden',
      rate_limited: 'Zu viele Versuche. Bitte warte eine Minute.',
      account_not_found: 'Dein Konto wurde nicht gefunden. Bitte wende dich an deine Betreuungsperson.',
    },
  },
  report: {
    categoryMaintenance: 'Technisches Problem',
    categoryMaintenanceDesc: 'Defekte Geräte, Wasserschäden, Heizung etc.',
    categoryConflict: 'Konflikt melden',
    categoryConflictDesc: 'Probleme mit Mitbewohnern oder Nachbarn',
    titleMaintenance: '🔧 Technisches Problem melden',
    titleConflict: '💬 Konflikt melden',
    conflictSubtitle: 'Bei Problemen mit Mitbewohnern. Deine Meldung wird vertraulich behandelt.',
    typeLabel: 'Art des Problems',
    conflictTypeLabel: 'Art des Konflikts',
    selectPlaceholder: 'Bitte auswählen...',
    locationLabel: 'Wo ist das Problem?',
    involvedLabel: 'Betrifft (optional)',
    involvedPlaceholder: 'Möchte ich nicht sagen',
    involvedExternal: 'Jemand von ausserhalb',
    confidentialNote: 'Diese Information bleibt vertraulich',
    descriptionLabel: 'Beschreibung',
    conflictDescriptionLabel: 'Was ist passiert?',
    descriptionPlaceholder: 'Beschreibe das Problem möglichst genau...',
    conflictDescriptionPlaceholder: 'Beschreibe die Situation...',
    dateLabel: 'Wann ist es passiert?',
    severityLabel: 'Dringlichkeit',
    conflictSeverityLabel: 'Wie schwer wiegt es für dich?',
    mediationLabel: 'Ich wünsche ein Vermittlungsgespräch mit der Hausverwaltung',
    submitMaintenance: 'Problem melden',
    submitConflict: 'Konflikt melden',
    submitting: 'Wird gesendet...',
    successTitle: 'Meldung eingegangen',
    successMessage: 'Wir kümmern uns darum. Du wirst benachrichtigt, sobald es Neuigkeiten gibt.',
    errorGeneric: 'Meldung konnte nicht gesendet werden. Bitte erneut versuchen.',
    emergencyTitle: 'Bei Notfällen',
    emergencyMessage: 'Bei akuter Gefahr oder medizinischen Notfällen rufe sofort 112 an. Diese Meldung ist nicht für Notfälle gedacht.',
    noPlacement: 'Du hast noch keine Unterkunft zugewiesen bekommen.',
    noPlacementContact: CONTACT_FALLBACK_SENTENCE,
    maintenanceTypes: [
      { value: 'PLUMBING', label: 'Sanitär (WC, Dusche, Wasserhahn)' },
      { value: 'ELECTRICAL', label: 'Elektrik (Licht, Steckdosen)' },
      { value: 'HEATING_COOLING', label: 'Heizung / Klima' },
      { value: 'APPLIANCE', label: 'Gerät defekt (Kühlschrank, Herd etc.)' },
      { value: 'STRUCTURAL', label: 'Bauschaden (Fenster, Türen, Boden)' },
      { value: 'PEST_CONTROL', label: 'Schädlinge' },
      { value: 'SECURITY_SYSTEM', label: 'Sicherheit (Schloss, Tür)' },
      { value: 'GENERAL_MAINTENANCE', label: 'Sonstiges' },
    ],
    conflictTypes: [
      { value: 'NOISE_COMPLAINT', label: 'Lärm' },
      { value: 'CLEANLINESS_DISPUTE', label: 'Sauberkeit' },
      { value: 'SPACE_DISPUTE', label: 'Platz / Nutzung gemeinsamer Räume' },
      { value: 'SCHEDULE_CONFLICT', label: 'Zeitliche Konflikte (Bad, Küche)' },
      { value: 'PERSONAL_CONFLICT', label: 'Persönlicher Konflikt' },
      { value: 'CULTURAL_FRICTION', label: 'Kulturelle Missverständnisse' },
      { value: 'SAFETY_CONCERN', label: 'Sicherheitsbedenken' },
      { value: 'OTHER', label: 'Sonstiges' },
    ],
    locations: [
      { value: 'room', label: 'Mein Zimmer' },
      { value: 'bathroom', label: 'Badezimmer' },
      { value: 'kitchen', label: 'Küche' },
      { value: 'common', label: 'Gemeinschaftsraum' },
      { value: 'entrance', label: 'Eingang / Flur' },
      { value: 'other', label: 'Anderer Ort' },
    ],
    severityOptions: {
      MAINTENANCE: [
        { value: 'LOW', label: 'Kann warten', icon: '🟢' },
        { value: 'MEDIUM', label: 'Bald beheben', icon: '🟡' },
        { value: 'HIGH', label: 'Dringend', icon: '🟠' },
        { value: 'CRITICAL', label: 'Notfall', icon: '🔴' },
      ],
      INTERPERSONAL: [
        { value: 'LOW', label: 'Störend', desc: 'Aber ich komme zurecht' },
        { value: 'MEDIUM', label: 'Belastend', desc: 'Beeinträchtigt meinen Alltag' },
        { value: 'HIGH', label: 'Sehr belastend', desc: 'Brauche Unterstützung' },
        { value: 'CRITICAL', label: 'Unerträglich', desc: 'Dringende Hilfe nötig' },
      ],
    },
    quickTitle: 'Schnell melden',
    quickSubtitle: 'Typische Fälle mit einem Klick vorbefüllen',
    resetTemplate: 'Vorlage zurücksetzen',
    templates: {
      urgentRepair: {
        label: '🔧 Dringende Reparatur',
        description: 'Dringender Defekt: Was ist kaputt, seit wann, und was ist aktuell eingeschränkt?',
      },
      noise: {
        label: '🔊 Lärmkonflikt',
        description: 'Lärmbelastung: Zeitpunkt, Häufigkeit und eigene Versuche zur Klärung kurz dokumentieren.',
      },
      safety: {
        label: '🚨 Sicherheit',
        description: 'Sicherheitsbedenken: Risiko, Beteiligte und was sofort benötigt wird klar beschreiben.',
      },
    },
    transparency: {
      title: 'Transparenz',
      before: 'Nach dem Absenden wird deine Meldung als',
      open: 'offen',
      middle: 'geführt und später als',
      resolved: 'gelöst',
      after: 'markiert. In dringenden Fällen wird priorisiert reagiert.',
      /** The promise above is only kept if the resident can reach the list. */
      seeMine: 'Deine bisherigen Meldungen ansehen',
    },
    nextStepsTitle: 'Was passiert als Nächstes?',
    nextSteps: [
      'Dein Bericht ist gespeichert und für das Team sichtbar.',
      'Das Team priorisiert den Fall nach Dringlichkeit.',
      'Bei Rückfragen oder bei hoher Priorität meldet sich die Betreuung zeitnah.',
    ],
    successTip: 'Tipp: Unter "Meine Meldungen" im Dashboard siehst du, ob ein Bericht offen oder gelöst ist.',
  },
  preferences: {
    saving: 'Wird gespeichert...',
    saveButton: 'Einstellungen speichern',
    successTitle: 'Einstellungen gespeichert',
    successMessage: 'Deine Präferenzen wurden aktualisiert.',
    errorGeneric: 'Einstellungen konnten nicht gespeichert werden. Bitte erneut versuchen.',
    privacyTitle: 'Datenschutz',
    privacyMessage: 'Deine Angaben werden nur verwendet, um passende Mitbewohner zu finden. Sie werden nicht an Dritte weitergegeben. Du kannst deine Daten jederzeit ändern oder löschen lassen.',
    saveTip: 'Tipp: Speichere unten, sobald du fertig bist. Änderungen sind erst nach dem Speichern aktiv.',
    unsavedChanges: 'Nicht gespeicherte Änderungen vorhanden.',
    confirmDiscard: 'Änderungen verwerfen?',
    confirmDiscardBody: 'Nicht gespeicherte Eingaben gehen verloren.',
    confirmDiscardConfirm: 'Verwerfen',
    sections: {
      lifestyle: 'Lebensstil',
      social: 'Soziales',
      practical: 'Praktisches',
      roommatePrefs: 'Mitbewohner-Präferenzen',
    },
    fields: {
      sleepSchedule: 'Schlafrhythmus',
      noiseTolerance: 'Lärmtoleranz',
      cleanlinessPractice: 'Eigene Ordnung',
      cleanlinessExpectation: 'Erwartung an andere',
      chaosTolerance: 'Toleranz für Unordnung',
      socialStyle: 'Soziale Präferenz',
      privacyNeed: 'Privatsphäre',
      languages: 'Sprachen',
      smoking: 'Rauchen',
      petTolerance: 'Haustiere OK',
      sharedBathroom: 'Geteiltes Bad OK',
      sharedKitchen: 'Geteilte Küche OK',
      diet: 'Ernährung',
      preferredAgeRange: 'Bevorzugte Altersgruppe',
      noPref: 'Keine Präferenz',
      similarAge: 'Ähnliches Alter wie ich',
      culturalPref: 'Kulturelle Präferenz',
      sameRegion: 'Aus meiner Region',
      differentRegion: 'Aus anderen Regionen (zum Kennenlernen)',
      additionalPrefs: 'Zusätzliche Wünsche',
    },
    hints: {
      noiseTolerance: 'Wie empfindlich bist du gegenüber Geräuschen?',
      cleanlinessPractice: 'Wie ordentlich hältst du deinen eigenen Bereich?',
      cleanlinessExpectation: 'Wie ordentlich sollten die anderen sein?',
      chaosTolerance: 'Wie gut kannst du mit Unordnung leben?',
      privacyNeed: 'Wie viel Rückzugsort brauchst du?',
      languages: 'Welche Sprachen sprichst du?',
      roommatePrefs: 'Optional: Hast du besondere Wünsche für deine Mitbewohner?',
      culturalPref: 'Dies ist nur eine Präferenz, keine Garantie',
      additionalPrefsPlaceholder: "z.B. 'Ich arbeite Nachtschicht', 'Ich habe Allergien gegen Katzen'...",
    },
  },
  satisfaction: {
    title: 'Wie geht es dir in deiner Unterkunft?',
    subtitle: 'Dein vertrauliches Feedback hilft uns, Probleme früh zu erkennen',
    privacyNote: 'Vertraulich gespeichert · Wird nicht mit deinem Namen verknüpft',
    thankYouTitle: 'Danke für dein Feedback!',
    thankYouMessage: 'Deine Rückmeldung hilft uns, die Unterkunft zu verbessern',
    concernsForwarded: 'Wir haben deine Anliegen weitergeleitet',
    newFeedback: 'Neues Feedback',
    lastFeedback: 'Letztes Feedback',
    today: 'Heute',
  },
  dashboard: {
    housing: 'Deine Unterkunft',
    noHousing: 'Du hast noch keine Unterkunft zugewiesen bekommen',
    noHousingHint: 'Bitte kontaktiere deinen Betreuer',
    noHousingContact: CONTACT_FALLBACK_SENTENCE,
    onboarding: {
      title: 'Dein Profil ist erstellt',
      subtitle: 'Wir suchen die passende Unterkunft für dich',
      steps: [
        'Profil erstellt',
        'Einstellungen vervollständigen',
        'Unterkunft suchen',
        'Einzug',
      ],
      completePreferences: 'Einstellungen vervollständigen',
      completePreferencesHint: 'Je mehr wir über dich wissen, desto besser können wir passende Mitbewohner finden.',
      browseHousing: 'Verfügbare Unterkünfte ansehen',
      browseHousingHint: 'Sieh dir Unterkünfte an, die zu deinen Präferenzen passen.',
      preferencesComplete: 'Einstellungen gespeichert',
    },
    houseRules: 'Hausregeln',
    quietHours: 'Ruhezeit',
    smokingAllowed: 'Rauchen erlaubt',
    noSmoking: 'Nichtraucher',
    petsAllowed: 'Haustiere erlaubt',
    noPets: 'Keine Haustiere',
    roommates: 'Mitbewohner',
    showAll: 'Alle anzeigen',
    myReports: 'Deine Meldungen',
    newReport: 'Neu melden',
    noReports: 'Keine Meldungen',
    openMaintenance: 'Offene Wartung im Gebäude',
    resolved: 'Erledigt',
    open: 'Offen',
    inProgress: 'in Bearbeitung',
    reportResolved: 'Erledigt',
    reportPending: 'Das Team prüft diese Meldung aktuell.',
    reportAnswer: 'Antwort der Betreuung',
    reported: 'Gemeldet',
    active: 'Aktiv',
    moveIn: 'Einzug',
    rooms: 'Zimmer',
    compatibility: 'Kompatibilität',
    housingBrowse: {
      compatibility: 'Kompatibilität',
      spots: 'Freie Plätze',
      currentRoommates: 'Aktuelle Bewohner',
      strengths: 'Passt gut',
      concerns: 'Beachten',
      emptyUnit: 'Noch keine Bewohner — du wärst die erste Person!',
      noMatches: 'Aktuell keine passenden Unterkünfte verfügbar. Bitte kontaktiere dein Betreuungsteam.',
      contactHint: 'Interessiert? Sprich mit deinem Betreuungsteam über diese Unterkunft.',
      features: {
        sharedKitchen: 'Gemeinschaftsküche',
        privateKitchen: 'Eigene Küche',
        smokingAllowed: 'Rauchen erlaubt',
        noSmoking: 'Nichtraucher',
        petsAllowed: 'Haustiere erlaubt',
        wheelchairAccess: 'Rollstuhlgerecht',
        groundFloor: 'Erdgeschoss',
        elevator: 'Aufzug',
      },
    },
    quickActions: {
      chores: { icon: '📋', title: 'Aufgaben', desc: 'Haushaltsaufgaben verwalten' },
      report: { icon: '🔧', title: 'Problem melden', desc: 'Defekte oder Wartung melden' },
      roommates: { icon: '👥', title: 'Mitbewohner', desc: 'Infos zu deinen Mitbewohnern' },
      learning: { icon: '🎓', title: 'Lernen', desc: 'Kurse, Nachweise, Freiwilligenarbeit' },
      preferences: { icon: '⚙️', title: 'Einstellungen', desc: 'Deine Präferenzen anpassen' },
    },
    prioritySections: {
      now: {
        heading: 'Jetzt',
        taskSingular: 'Aufgabe braucht Aufmerksamkeit.',
        taskPlural: 'Aufgaben brauchen Aufmerksamkeit.',
        noTasks: 'Keine dringenden Aufgaben offen.',
      },
      next: {
        heading: 'Als Nächstes',
        desc: 'Melde Probleme früh und halte deine Präferenzen aktuell.',
      },
      info: {
        heading: 'Info',
        desc: 'Schau dir deine Mitbewohner an und bleib über den Gebäudestatus informiert.',
      },
    },
  },
  landing: {
    hero: 'Willkommen bei Mein Zuhause',
    heroSubtitle: 'Hier findest du alles rund um deine Unterkunft — Mitbewohner, Meldungen und Einstellungen an einem Ort.',
    features: [
      {
        icon: '🏠',
        title: 'Deine Unterkunft',
        desc: 'Alle Infos zu deinem Zuhause, deinen Mitbewohnern und den Hausregeln.',
      },
      {
        icon: '💬',
        title: 'Probleme melden',
        desc: 'Defekte, Konflikte oder Anliegen direkt und einfach an die Verwaltung melden.',
      },
      {
        icon: '⚙️',
        title: 'Deine Einstellungen',
        desc: 'Schlafzeiten, Sprachen, Vorlieben — damit wir passende Mitbewohner finden.',
      },
    ],
    loginTitle: 'Bereits registriert?',
    loginDesc: 'Melde dich mit deinem Bewohnercode an',
    registerTitle: 'Neu hier?',
    registerDesc: 'Erstelle in 30 Sekunden dein Profil',
    registerButton: 'Profil erstellen',
    registerSuccess: 'Profil erstellt! Dein Code ist:',
    registerAgeRange: 'Altersgruppe',
    registerGender: 'Geschlecht',
    registerFamilyStatus: 'Familienstatus',
    registerLanguages: 'Sprachen (optional)',
    registerCreating: 'Wird erstellt...',
    registerSelectPlaceholder: 'Bitte auswählen...',
    staffLink: 'Mitarbeitende? Zum Mitarbeiter-Login',
  },
  transfer: {
    title: 'Verlegung anfragen',
    subtitle: 'Möchtest du in eine andere Unterkunft wechseln?',
    reasonLabel: 'Warum möchtest du verlegt werden?',
    reasonPlaceholder: 'Beschreibe den Grund für deinen Verlegungswunsch...',
    targetUnitLabel: 'Wunsch-Unterkunft (optional)',
    targetUnitPlaceholder: 'Keine Präferenz',
    submit: 'Anfrage senden',
    submitting: 'Wird gesendet...',
    pendingTitle: 'Anfrage eingereicht',
    pendingMessage: 'Deine Verlegungsanfrage wird vom Team bearbeitet. Du wirst benachrichtigt, sobald es Neuigkeiten gibt.',
    noPlacement: 'Du hast noch keine Unterkunft zugewiesen bekommen.',
    successTitle: 'Anfrage gesendet',
    successMessage: 'Deine Verlegungsanfrage wurde erfolgreich eingereicht.',
    successNextStepsTitle: 'Wie geht es weiter?',
    successNextSteps: [
      'Die Betreuung sieht deine Anfrage im Team-Posteingang.',
      'Bei Rückfragen oder bei einem Entscheid meldet sich das Team bei dir.',
      'Wenn sich deine Situation ändert, kannst du zusätzlich eine Nachricht schreiben.',
    ],
    successToMessages: 'Nachricht an die Betreuung',
    successToOverview: 'Zur Übersicht',
    navLabel: 'Verlegung',
    currentUnit: 'Aktuelle Unterkunft',
    decisionTitle: 'Antwort auf deine Anfrage',
    yourReason: 'Dein Grund',
    staffNote: 'Nachricht der Betreuung',
    decidedOn: 'Entschieden am',
  },
  help: {
    faqTitle: 'Häufig gestellte Fragen',
    contactTitle: 'Kontakt',
    emergencyTitle: 'Notfall',
    emergencyDesc: 'Bei Notfällen oder akuter Gefahr wende dich sofort an:',
    // Real channels from the signed Hausordnung — SSOT: lib/config/organization.ts
    emergency: {
      police: ORG_CONTACT.emergency.police,
      policeNumber: ORG_CONTACT.emergency.policeNumber,
      aoz: ORG_CONTACT.emergency.orgLabel,
      aozNumber: ORG_CONTACT.emergency.orgNumber,
      aozHours: ORG_CONTACT.emergency.orgHours,
    },
    contacts: ORG_CONTACT_CHANNELS,
    faqs: [
      {
        question: 'Wie funktioniert die Zimmerverteilung?',
        answer: 'Wir berücksichtigen verschiedene Faktoren wie Schlafrhythmus, Lärmtoleranz und Sprachkenntnisse, um passende Mitbewohner zu finden. Je genauer deine Angaben, desto besser können wir dich platzieren.',
      },
      {
        question: 'Kann ich meine Präferenzen ändern?',
        answer: 'Ja, du kannst deine Präferenzen jederzeit unter "Einstellungen" aktualisieren. Änderungen werden bei zukünftigen Platzierungen berücksichtigt.',
      },
      {
        question: 'Was passiert bei einem Konflikt mit Mitbewohnern?',
        answer: 'Bitte melde Probleme über "Problem melden" im Portal. Wir nehmen alle Meldungen ernst und suchen gemeinsam nach Lösungen.',
      },
      {
        question: 'Wie lange dauert eine Platzierung?',
        answer: 'Die Dauer hängt von deiner individuellen Situation ab. Wir informieren dich über voraussichtliche Zeiträume und mögliche Änderungen.',
      },
      {
        question: 'Kann ich einen Umzug beantragen?',
        answer: 'Bei berechtigten Gründen kannst du einen Umzug beantragen. Sprich mit deiner Betreuungsperson oder nutze das Meldeformular.',
      },
      {
        question: 'Was bedeuten die Kompatibilitätswerte?',
        answer: 'Die Werte zeigen, wie gut du voraussichtlich mit anderen Bewohnern zusammenpasst. Hohe Werte bedeuten ähnliche Präferenzen bei Schlaf, Sauberkeit und Sozialverhalten.',
      },
      {
        question: 'Werden meine Daten geschützt?',
        answer: 'Ja, deine Daten werden nur zur Zimmerzuteilung verwendet und nicht an Dritte weitergegeben. Du kannst deine Daten jederzeit einsehen oder löschen lassen.',
      },
      {
        question: 'An wen wende ich mich bei technischen Problemen?',
        answer: 'Bei technischen Problemen mit dem Portal wende dich bitte an die unten stehenden Kontakte oder sprich deine Betreuungsperson an.',
      },
    ],
    quickLinks: [
      { href: '/portal/preferences', icon: '⚙️', title: 'Einstellungen', desc: 'Präferenzen anpassen' },
      { href: '/portal/report', icon: '📝', title: 'Problem melden', desc: 'Vorfall oder Anliegen' },
    ],
  },
  roommates: {
    noRoommates: 'Du hast derzeit keine Mitbewohner',
    aloneMessage: 'Du hast die Unterkunft für dich allein',
    tipsTitle: 'Tipps für das Zusammenleben',
    tips: [
      { icon: '🗣️', title: 'Kommunikation', desc: 'Sprich Probleme frühzeitig an, bevor sie grösser werden' },
      { icon: '🤝', title: 'Respekt', desc: 'Respektiere die Privatsphäre und Ruhezeiten deiner Mitbewohner' },
      { icon: '🧹', title: 'Sauberkeit', desc: 'Halte gemeinsame Räume sauber und räume nach dir auf' },
      { icon: '📅', title: 'Absprachen', desc: 'Trefft klare Vereinbarungen über Küche, Bad und Gemeinschaftsräume' },
    ],
    conflictTitle: 'Bei Konflikten',
    conflictSteps: [
      'Direktes Gespräch: Versuche zuerst, das Problem direkt mit deinem Mitbewohner zu besprechen.',
      'Vermittlung: Wenn das nicht klappt, kann die Hausverwaltung vermitteln.',
    ],
    conflictReport: 'Bei ernsthaften Problemen kannst du einen',
    conflictReportLink: 'Vorfall melden',
    strengths: 'Stärken',
    concerns: 'Achtung',
    compatible: 'kompatibel',
    isSmoker: 'Raucher',
    noPlacement: 'Du hast noch keine Unterkunft zugewiesen bekommen.',
    noPlacementContact: CONTACT_FALLBACK_SENTENCE,
    roommateCount: (n: number) => n === 1 ? 'Du wohnst mit 1 Person zusammen' : `Du wohnst mit ${n} Personen zusammen`,
    ageYears: 'Jahre',
    scoreLevels: {
      excellent: 'Sehr gut',
      good: 'Gut',
      moderate: 'OK',
      low: 'Herausfordernd',
      critical: 'Schwierig',
    },
  },
  pendingChores: {
    title: 'Offene Aufgaben',
    requestOpen: 'Anfrage offen',
  },
  expenses: {
    title: 'Gemeinsame Ausgaben',
    subtitle: 'Wer hat was bezahlt — und wer schuldet wem',
    balancesTitle: 'Kontostand',
    balancePositive: 'bekommt',
    balanceNegative: 'schuldet',
    balanceSettled: 'ausgeglichen',
    suggestedTitle: 'Vorschlag zum Ausgleich',
    /** Only grammatical with a PERSON as the subject: "Ana zahlt an Bea CHF 5". */
    suggestedPays: 'zahlt an',
    noDebts: 'Alles ausgeglichen — niemand schuldet etwas.',
    markPaid: 'Als bezahlt erfassen',
    /**
     * The confirm needs its own sentence — reusing `suggestedPays` here put the
     * AMOUNT in the subject slot and asked "CHF 16.65 zahlt an Fatima?".
     */
    markPaidConfirm: (amount: string, name: string) =>
      `${amount} an ${name} als bezahlt erfassen?`,
    addTitle: 'Ausgabe erfassen',
    descriptionLabel: 'Beschreibung',
    descriptionPlaceholder: 'z.B. Wocheneinkauf',
    amountLabel: 'Betrag (CHF)',
    amountPlaceholder: 'z.B. 24.50',
    amountInvalid: 'Bitte gib einen gültigen Betrag ein (z.B. 12.50)',
    categoryLabel: 'Kategorie',
    dateLabel: 'Datum',
    paidByLabel: 'Bezahlt von',
    participantsLabel: 'Aufteilen auf',
    participantsHint: 'Standard: alle Mitbewohner',
    submit: 'Speichern',
    historyTitle: 'Alle Ausgaben',
    settlementsTitle: 'Erfasste Zahlungen',
    delete: 'Löschen',
    deleteConfirm: 'Diese Ausgabe wirklich löschen?',
    empty: 'Noch keine Ausgaben erfasst',
    emptyHint: 'Erfasse den ersten gemeinsamen Einkauf, damit alle den Überblick behalten.',
    paidBy: 'bezahlt von',
    you: 'Du',
    settlementNoteLabel: 'Notiz (optional)',
    settlementRecorded: 'Zahlung erfasst',
    createdToast: 'Ausgabe erfolgreich gespeichert',
    settledToast: 'Zahlung erfolgreich erfasst',
    deletedToast: 'Ausgabe erfolgreich gelöscht',
    dashboardTitle: 'Ausgaben',
    dashboardCta: 'Alle Ausgaben anzeigen',
    dashboardBalance: 'Dein Kontostand',
    splitAcross: 'Aufgeteilt auf',
    splitAll: 'alle',
    each: 'je',
    recordedBy: 'erfasst von',
    statementTitle: 'Monatsabrechnung',
    statementSubtitle: 'Pro Monat: wer hat wie viel bezahlt und wie viel verbraucht',
    statementPerson: 'Person',
    statementPaid: 'Bezahlt',
    statementShare: 'Anteil',
    statementNet: 'Saldo',
    statementTotal: 'Total',
    statementExpenses: 'Ausgaben',
    statementNetHint:
      'Saldo = bezahlt minus Anteil. Plus heisst: hat in diesem Monat für andere vorgestreckt.',
  },
  apartment: {
    title: 'Unsere Wohnung',
    subtitle: 'Euer Zuhause auf einen Blick',
    nameLabel: 'Name der Wohnung',
    namePlaceholder: 'z.B. Singapur',
    nameHint: 'Gebt eurer Wohnung einen Namen — alle Mitbewohner sehen ihn.',
    nameEdit: 'Namen ändern',
    nameSave: 'Speichern',
    unnamed: 'Noch ohne Namen',
    address: 'Adresse',
    roomsTitle: 'Zimmer',
    roomFallback: 'Zimmer',
    freeBed: 'Freier Platz',
    residentsTitle: 'Wer hier wohnt',
    quietHours: 'Ruhezeit',
  },
  profile: {
    title: 'Dein Profil',
    subtitle: 'Zeig deinen Mitbewohnern, wer du bist — alles freiwillig',
    codeLabel: 'Dein Login-Code',
    codeHint: 'Der Code bleibt dein Login. Name, Foto und Text sind freiwillig und jederzeit änderbar.',
    displayNameLabel: 'Name',
    displayNamePlaceholder: 'z.B. Georgy',
    bioLabel: 'Über mich',
    bioPlaceholder: 'z.B. Ich koche gern und stehe früh auf.',
    photoLabel: 'Foto',
    photoUpload: 'Foto auswählen',
    photoRemove: 'Foto entfernen',
    photoHint: 'JPG, PNG oder WebP — wird automatisch verkleinert.',
    visibleTo: 'Sichtbar für deine Mitbewohner und die Verwaltung.',
    savedToast: 'Profil erfolgreich gespeichert',
    photoUpdatedToast: 'Foto erfolgreich aktualisiert',
    photoRemovedToast: 'Foto erfolgreich entfernt',
    /**
     * The visibility control. The staff line is stated on every option rather
     * than hidden in small print: a resident deciding what to share is owed
     * the fact that the people supporting them can always see it.
     */
    visibilityLabel: 'Wer sieht dein Profil?',
    visibilityStaffNote: 'Die Betreuung sieht dein Profil immer — sie muss wissen, wen sie unterstützt.',
    visibilityOptions: {
      PRIVATE: 'Nur ich',
      ROOMMATES: 'Meine Mitbewohnenden',
      RESIDENTS: 'Alle Bewohnenden',
    },
    visibilityHints: {
      PRIVATE: 'Niemand ausser dir und der Betreuung.',
      ROOMMATES: 'Die Leute, mit denen du zusammenwohnst.',
      RESIDENTS: 'Auch Bewohnende aus anderen Wohnungen.',
    },
  },
  error: {
    title: 'Etwas ist schiefgelaufen',
    message: 'Beim Laden der Portalseite ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    retry: 'Erneut versuchen',
    home: 'Zur Startseite',
  },
} as const
