/**
 * Portal labels: resident-facing UI text
 */

export const PORTAL_LABELS = {
  title: 'Mein Zuhause',
  nav: {
    overview: 'Übersicht',
    roommates: 'Mitbewohner',
    chores: 'Aufgaben',
    report: 'Melden',
    housing: 'Unterkünfte',
    activities: 'Aktivitäten',
    preferences: 'Einstellungen',
    help: 'Hilfe',
    logout: 'Abmelden',
  },
  emergency: 'Bei Notfällen: 112 oder Hausverwaltung kontaktieren',
  pages: {
    dashboard: 'Willkommen',
    dashboardSubtitle: 'Hier findest du alles zu deiner Unterkunft',
    roommates: 'Deine Mitbewohner',
    report: 'Problem melden',
    reportSubtitle: 'Melde technische Probleme oder Konflikte',
    preferences: 'Deine Einstellungen',
    preferencesSubtitle: 'Diese Angaben helfen uns, passende Mitbewohner zu finden',
    help: 'Hilfe & FAQ',
    helpSubtitle: 'Antworten auf häufig gestellte Fragen und Kontaktinformationen',
    housing: 'Verfügbare Unterkünfte',
    housingSubtitle: 'Unterkünfte, die zu deinen Einstellungen passen',
    activities: 'Aktivitäten in Zürich',
    activitiesSubtitle: 'Kostenlose und günstige Angebote für dich in der Region',
  },
  activities: {
    allCategories: 'Alle Kategorien',
    showAll: 'Alle Aktivitäten anzeigen',
    costFree: 'Kostenlos',
    costReduced: 'Ermässigt',
    costPaid: 'Kostenpflichtig',
    website: 'Website öffnen',
    phone: 'Anrufen',
    noResults: 'Keine Aktivitäten in dieser Kategorie gefunden.',
    dashboardTitle: 'Aktivitäten in Zürich',
    dashboardSubtitle: 'Kostenlose & günstige Angebote',
    dashboardCta: 'Alle Angebote anzeigen',
  },
  form: {
    submit: 'Absenden',
    submitting: 'Wird gesendet...',
    saving: 'Wird gespeichert...',
    saved: 'Gespeichert',
    cancel: 'Abbrechen',
    back: '← Zurück zur Übersicht',
    errorGeneric: 'Ein Fehler ist aufgetreten. Bitte erneut versuchen.',
    successGeneric: 'Erfolgreich gespeichert',
  },
  login: {
    title: 'Mein Zuhause',
    subtitle: 'Gib deinen Bewohnercode ein, um fortzufahren',
    placeholder: 'Dein Code (z.B. RES-001)',
    submit: 'Einloggen',
    hint: 'Deinen Code findest du auf deinem Willkommensbrief',
    errors: {
      code_required: 'Bitte Code eingeben',
      invalid_code: 'Code nicht gefunden',
      rate_limited: 'Zu viele Versuche. Bitte warte eine Minute.',
      account_not_found: 'Dein Konto wurde nicht gefunden. Bitte wende dich an deine Betreuungsperson.',
    },
  },
  report: {
    categoryMaintenance: 'Technisches Problem',
    categoryMaintenanceDesc: 'Defekte Geräte, Wasserschäden, Heizung etc.',
    categoryConflict: 'Konflikt melden',
    categoryConflictDesc: 'Probleme mit Mitbewohnern oder Nachbarn',
    titleMaintenance: '🔧 Technisches Problem melden',
    titleConflict: '💬 Konflikt melden',
    conflictSubtitle: 'Bei Problemen mit Mitbewohnern. Deine Meldung wird vertraulich behandelt.',
    typeLabel: 'Art des Problems',
    conflictTypeLabel: 'Art des Konflikts',
    selectPlaceholder: 'Bitte auswählen...',
    locationLabel: 'Wo ist das Problem?',
    involvedLabel: 'Betrifft (optional)',
    involvedPlaceholder: 'Möchte ich nicht sagen',
    involvedExternal: 'Jemand von ausserhalb',
    confidentialNote: 'Diese Information bleibt vertraulich',
    descriptionLabel: 'Beschreibung',
    conflictDescriptionLabel: 'Was ist passiert?',
    descriptionPlaceholder: 'Beschreibe das Problem möglichst genau...',
    conflictDescriptionPlaceholder: 'Beschreibe die Situation...',
    dateLabel: 'Wann ist es passiert?',
    severityLabel: 'Dringlichkeit',
    conflictSeverityLabel: 'Wie schwer wiegt es für dich?',
    mediationLabel: 'Ich wünsche ein Vermittlungsgespräch mit der Hausverwaltung',
    submitMaintenance: 'Problem melden',
    submitConflict: 'Konflikt melden',
    submitting: 'Wird gesendet...',
    successTitle: 'Meldung eingegangen',
    successMessage: 'Wir kümmern uns darum. Du wirst benachrichtigt, sobald es Neuigkeiten gibt.',
    errorGeneric: 'Meldung konnte nicht gesendet werden. Bitte erneut versuchen.',
    emergencyTitle: 'Bei Notfällen',
    emergencyMessage: 'Bei akuter Gefahr oder medizinischen Notfällen rufe sofort 112 an. Diese Meldung ist nicht für Notfälle gedacht.',
    noPlacement: 'Du hast noch keine Unterkunft zugewiesen bekommen.',
    noPlacementContact: 'Kontaktiere uns: 044 415 66 66 (Mo-Fr 8:00-17:00) oder wohnen@aoz.ch',
    maintenanceTypes: [
      { value: 'PLUMBING', label: 'Sanitär (WC, Dusche, Wasserhahn)' },
      { value: 'ELECTRICAL', label: 'Elektrik (Licht, Steckdosen)' },
      { value: 'HEATING_COOLING', label: 'Heizung / Klima' },
      { value: 'APPLIANCE', label: 'Gerät defekt (Kühlschrank, Herd etc.)' },
      { value: 'STRUCTURAL', label: 'Bauschaden (Fenster, Türen, Boden)' },
      { value: 'PEST_CONTROL', label: 'Schädlinge' },
      { value: 'SECURITY_SYSTEM', label: 'Sicherheit (Schloss, Tür)' },
      { value: 'GENERAL_MAINTENANCE', label: 'Sonstiges' },
    ],
    conflictTypes: [
      { value: 'NOISE_COMPLAINT', label: 'Lärm' },
      { value: 'CLEANLINESS_DISPUTE', label: 'Sauberkeit' },
      { value: 'SPACE_DISPUTE', label: 'Platz / Nutzung gemeinsamer Räume' },
      { value: 'SCHEDULE_CONFLICT', label: 'Zeitliche Konflikte (Bad, Küche)' },
      { value: 'PERSONAL_CONFLICT', label: 'Persönlicher Konflikt' },
      { value: 'CULTURAL_FRICTION', label: 'Kulturelle Missverständnisse' },
      { value: 'SAFETY_CONCERN', label: 'Sicherheitsbedenken' },
      { value: 'OTHER', label: 'Sonstiges' },
    ],
    locations: [
      { value: 'room', label: 'Mein Zimmer' },
      { value: 'bathroom', label: 'Badezimmer' },
      { value: 'kitchen', label: 'Küche' },
      { value: 'common', label: 'Gemeinschaftsraum' },
      { value: 'entrance', label: 'Eingang / Flur' },
      { value: 'other', label: 'Anderer Ort' },
    ],
    severityOptions: {
      MAINTENANCE: [
        { value: 'LOW', label: 'Kann warten', icon: '🟢' },
        { value: 'MEDIUM', label: 'Bald beheben', icon: '🟡' },
        { value: 'HIGH', label: 'Dringend', icon: '🟠' },
        { value: 'CRITICAL', label: 'Notfall', icon: '🔴' },
      ],
      INTERPERSONAL: [
        { value: 'LOW', label: 'Störend', desc: 'Aber ich komme zurecht' },
        { value: 'MEDIUM', label: 'Belastend', desc: 'Beeinträchtigt meinen Alltag' },
        { value: 'HIGH', label: 'Sehr belastend', desc: 'Brauche Unterstützung' },
        { value: 'CRITICAL', label: 'Unerträglich', desc: 'Dringende Hilfe nötig' },
      ],
    },
  },
  preferences: {
    saving: 'Wird gespeichert...',
    saveButton: 'Einstellungen speichern',
    successTitle: 'Einstellungen gespeichert',
    successMessage: 'Deine Präferenzen wurden aktualisiert.',
    errorGeneric: 'Einstellungen konnten nicht gespeichert werden. Bitte erneut versuchen.',
    privacyTitle: 'Datenschutz',
    privacyMessage: 'Deine Angaben werden nur verwendet, um passende Mitbewohner zu finden. Sie werden nicht an Dritte weitergegeben. Du kannst deine Daten jederzeit ändern oder löschen lassen.',
  },
  satisfaction: {
    title: 'Wie geht es dir in deiner Unterkunft?',
    subtitle: 'Dein vertrauliches Feedback hilft uns, Probleme früh zu erkennen',
    privacyNote: 'Vertraulich gespeichert · Wird nicht mit deinem Namen verknüpft',
    thankYouTitle: 'Danke für dein Feedback!',
    thankYouMessage: 'Deine Rückmeldung hilft uns, die Unterkunft zu verbessern',
    concernsForwarded: 'Wir haben deine Anliegen weitergeleitet',
    newFeedback: 'Neues Feedback',
    lastFeedback: 'Letztes Feedback',
    today: 'Heute',
  },
  dashboard: {
    housing: 'Deine Unterkunft',
    noHousing: 'Du hast noch keine Unterkunft zugewiesen bekommen',
    noHousingHint: 'Bitte kontaktiere deinen Betreuer',
    noHousingContact: 'Allgemeine Anfragen: 044 415 66 66 (Mo-Fr 8:00-17:00) oder wohnen@aoz.ch',
    onboarding: {
      title: 'Dein Profil ist erstellt',
      subtitle: 'Wir suchen die passende Unterkunft für dich',
      steps: [
        'Profil erstellt',
        'Einstellungen vervollständigen',
        'Unterkunft suchen',
        'Einzug',
      ],
      completePreferences: 'Einstellungen vervollständigen',
      completePreferencesHint: 'Je mehr wir über dich wissen, desto besser können wir passende Mitbewohner finden.',
      browseHousing: 'Verfügbare Unterkünfte ansehen',
      browseHousingHint: 'Sieh dir Unterkünfte an, die zu deinen Präferenzen passen.',
      preferencesComplete: 'Einstellungen gespeichert',
    },
    houseRules: 'Hausregeln',
    quietHours: 'Ruhezeit',
    smokingAllowed: 'Rauchen erlaubt',
    noSmoking: 'Nichtraucher',
    petsAllowed: 'Haustiere erlaubt',
    noPets: 'Keine Haustiere',
    roommates: 'Mitbewohner',
    showAll: 'Alle anzeigen',
    myReports: 'Deine Meldungen',
    newReport: 'Neu melden',
    noReports: 'Keine Meldungen',
    openMaintenance: 'Offene Wartung im Gebäude',
    resolved: 'Erledigt',
    open: 'Offen',
    inProgress: 'in Bearbeitung',
    reportResolved: 'Erledigt',
    reportPending: 'Das Team prüft diese Meldung aktuell.',
    reported: 'Gemeldet',
    active: 'Aktiv',
    moveIn: 'Einzug',
    rooms: 'Zimmer',
    compatibility: 'Kompatibilität',
    housingBrowse: {
      compatibility: 'Kompatibilität',
      spots: 'Freie Plätze',
      currentRoommates: 'Aktuelle Bewohner',
      strengths: 'Passt gut',
      concerns: 'Beachten',
      emptyUnit: 'Noch keine Bewohner — du wärst die erste Person!',
      noMatches: 'Aktuell keine passenden Unterkünfte verfügbar. Bitte kontaktiere dein Betreuungsteam.',
      contactHint: 'Interessiert? Sprich mit deinem Betreuungsteam über diese Unterkunft.',
      features: {
        sharedKitchen: 'Gemeinschaftsküche',
        privateKitchen: 'Eigene Küche',
        smokingAllowed: 'Rauchen erlaubt',
        noSmoking: 'Nichtraucher',
        petsAllowed: 'Haustiere erlaubt',
        wheelchairAccess: 'Rollstuhlgerecht',
        groundFloor: 'Erdgeschoss',
        elevator: 'Aufzug',
      },
    },
    quickActions: {
      chores: { icon: '📋', title: 'Aufgaben', desc: 'Haushaltsaufgaben verwalten' },
      report: { icon: '🔧', title: 'Problem melden', desc: 'Defekte oder Wartung melden' },
      roommates: { icon: '👥', title: 'Mitbewohner', desc: 'Infos zu deinen Mitbewohnern' },
      preferences: { icon: '⚙️', title: 'Einstellungen', desc: 'Deine Präferenzen anpassen' },
    },
    prioritySections: {
      now: {
        heading: 'Jetzt',
        taskSingular: 'Aufgabe braucht Aufmerksamkeit.',
        taskPlural: 'Aufgaben brauchen Aufmerksamkeit.',
        noTasks: 'Keine dringenden Aufgaben offen.',
      },
      next: {
        heading: 'Als Nächstes',
        desc: 'Melden Sie Probleme früh und halten Sie Ihre Präferenzen aktuell.',
      },
      info: {
        heading: 'Info',
        desc: 'Mitbewohner- und Gebäudestatus helfen bei der Planung des Alltags.',
      },
    },
  },
  landing: {
    hero: 'Willkommen bei Mein Zuhause',
    heroSubtitle: 'Hier findest du alles rund um deine Unterkunft — Mitbewohner, Meldungen und Einstellungen an einem Ort.',
    features: [
      {
        icon: '🏠',
        title: 'Deine Unterkunft',
        desc: 'Alle Infos zu deinem Zuhause, deinen Mitbewohnern und den Hausregeln.',
      },
      {
        icon: '💬',
        title: 'Probleme melden',
        desc: 'Defekte, Konflikte oder Anliegen direkt und einfach an die Verwaltung melden.',
      },
      {
        icon: '⚙️',
        title: 'Deine Einstellungen',
        desc: 'Schlafzeiten, Sprachen, Vorlieben — damit wir passende Mitbewohner finden.',
      },
    ],
    loginTitle: 'Bereits registriert?',
    loginDesc: 'Melde dich mit deinem Bewohnercode an',
    registerTitle: 'Neu hier?',
    registerDesc: 'Erstelle in 30 Sekunden dein Profil',
    registerButton: 'Profil erstellen',
    registerSuccess: 'Profil erstellt! Dein Code ist:',
    registerAgeRange: 'Altersgruppe',
    registerGender: 'Geschlecht',
    registerFamilyStatus: 'Familienstatus',
    registerLanguages: 'Sprachen (optional)',
    registerCreating: 'Wird erstellt...',
    registerSelectPlaceholder: 'Bitte auswählen...',
    staffLink: 'Mitarbeitende? Zum Mitarbeiter-Login',
  },
  transfer: {
    title: 'Verlegung anfragen',
    subtitle: 'Möchtest du in eine andere Unterkunft wechseln?',
    reasonLabel: 'Warum möchtest du verlegt werden?',
    reasonPlaceholder: 'Beschreibe den Grund für deinen Verlegungswunsch...',
    targetUnitLabel: 'Wunsch-Unterkunft (optional)',
    targetUnitPlaceholder: 'Keine Präferenz',
    submit: 'Anfrage senden',
    submitting: 'Wird gesendet...',
    pendingTitle: 'Anfrage eingereicht',
    pendingMessage: 'Deine Verlegungsanfrage wird vom Team bearbeitet. Du wirst benachrichtigt, sobald es Neuigkeiten gibt.',
    noPlacement: 'Du hast noch keine Unterkunft zugewiesen bekommen.',
    successTitle: 'Anfrage gesendet',
    successMessage: 'Deine Verlegungsanfrage wurde erfolgreich eingereicht.',
    navLabel: 'Verlegung',
  },
  roommates: {
    noRoommates: 'Du hast derzeit keine Mitbewohner',
    aloneMessage: 'Du hast die Unterkunft für dich allein',
    tipsTitle: 'Tipps für das Zusammenleben',
    tips: [
      { icon: '🗣️', title: 'Kommunikation', desc: 'Sprich Probleme frühzeitig an, bevor sie grösser werden' },
      { icon: '🤝', title: 'Respekt', desc: 'Respektiere die Privatsphäre und Ruhezeiten deiner Mitbewohner' },
      { icon: '🧹', title: 'Sauberkeit', desc: 'Halte gemeinsame Räume sauber und räume nach dir auf' },
      { icon: '📅', title: 'Absprachen', desc: 'Trefft klare Vereinbarungen über Küche, Bad und Gemeinschaftsräume' },
    ],
    conflictTitle: 'Bei Konflikten',
    conflictSteps: [
      'Direktes Gespräch: Versuche zuerst, das Problem direkt mit deinem Mitbewohner zu besprechen.',
      'Vermittlung: Wenn das nicht klappt, kann die Hausverwaltung vermitteln.',
    ],
    conflictReport: 'Bei ernsthaften Problemen kannst du einen',
    conflictReportLink: 'Vorfall melden',
    strengths: 'Stärken',
    concerns: 'Achtung',
    compatible: 'kompatibel',
    noPlacement: 'Du hast noch keine Unterkunft zugewiesen bekommen.',
    noPlacementContact: 'Kontaktiere uns: 044 415 66 66 (Mo-Fr 8:00-17:00) oder wohnen@aoz.ch',
  },
} as const
